/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __fpos_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __fpos_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__fpos_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___fpos_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__pos(int value) {
    arblibJNI.__fpos_t___pos_set(swigCPtr, this, value);
  }

  public int get__pos() {
    return arblibJNI.__fpos_t___pos_get(swigCPtr, this);
  }

  public void set__state(__mbstate_t value) {
    arblibJNI.__fpos_t___state_set(swigCPtr, this, __mbstate_t.getCPtr(value), value);
  }

  public __mbstate_t get__state() {
    long cPtr = arblibJNI.__fpos_t___state_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __mbstate_t(cPtr, false);
  }

  public __fpos_t() {
    this(arblibJNI.new___fpos_t(), true);
  }

}
