/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __gmp_randstate_struct__mp_algdata {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __gmp_randstate_struct__mp_algdata(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__gmp_randstate_struct__mp_algdata obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___gmp_randstate_struct__mp_algdata(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_mp_lc(SWIGTYPE_p_void value) {
    arblibJNI.__gmp_randstate_struct__mp_algdata__mp_lc_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void get_mp_lc() {
    long cPtr = arblibJNI.__gmp_randstate_struct__mp_algdata__mp_lc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public __gmp_randstate_struct__mp_algdata() {
    this(arblibJNI.new___gmp_randstate_struct__mp_algdata(), true);
  }

}
