/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __gmp_randstate_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __gmp_randstate_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__gmp_randstate_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___gmp_randstate_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_mp_seed(__mpz_struct value) {
    arblibJNI.__gmp_randstate_struct__mp_seed_set(swigCPtr, this, __mpz_struct.getCPtr(value), value);
  }

  public __mpz_struct get_mp_seed() {
    long cPtr = arblibJNI.__gmp_randstate_struct__mp_seed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __mpz_struct(cPtr, false);
  }

  public void set_mp_alg(gmp_randalg_t value) {
    arblibJNI.__gmp_randstate_struct__mp_alg_set(swigCPtr, this, value.swigValue());
  }

  public gmp_randalg_t get_mp_alg() {
    return gmp_randalg_t.swigToEnum(arblibJNI.__gmp_randstate_struct__mp_alg_get(swigCPtr, this));
  }

  public __gmp_randstate_struct() {
    this(arblibJNI.new___gmp_randstate_struct(), true);
  }

}
