/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __kernel_old_itimerval {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __kernel_old_itimerval(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__kernel_old_itimerval obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___kernel_old_itimerval(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIt_interval(__kernel_old_timeval value) {
    arblibJNI.__kernel_old_itimerval_it_interval_set(swigCPtr, this, __kernel_old_timeval.getCPtr(value), value);
  }

  public __kernel_old_timeval getIt_interval() {
    long cPtr = arblibJNI.__kernel_old_itimerval_it_interval_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __kernel_old_timeval(cPtr, false);
  }

  public void setIt_value(__kernel_old_timeval value) {
    arblibJNI.__kernel_old_itimerval_it_value_set(swigCPtr, this, __kernel_old_timeval.getCPtr(value), value);
  }

  public __kernel_old_timeval getIt_value() {
    long cPtr = arblibJNI.__kernel_old_itimerval_it_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __kernel_old_timeval(cPtr, false);
  }

  public __kernel_old_itimerval() {
    this(arblibJNI.new___kernel_old_itimerval(), true);
  }

}
