/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __kernel_fd_set {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __kernel_fd_set(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__kernel_fd_set obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___kernel_fd_set(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFds_bits(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.__kernel_fd_set_fds_bits_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getFds_bits() {
    long cPtr = arblibJNI.__kernel_fd_set_fds_bits_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public __kernel_fd_set() {
    this(arblibJNI.new___kernel_fd_set(), true);
  }

}
