/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __kernel_sock_timeval {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __kernel_sock_timeval(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__kernel_sock_timeval obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___kernel_sock_timeval(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTv_sec(long value) {
    arblibJNI.__kernel_sock_timeval_tv_sec_set(swigCPtr, this, value);
  }

  public long getTv_sec() {
    return arblibJNI.__kernel_sock_timeval_tv_sec_get(swigCPtr, this);
  }

  public void setTv_usec(long value) {
    arblibJNI.__kernel_sock_timeval_tv_usec_set(swigCPtr, this, value);
  }

  public long getTv_usec() {
    return arblibJNI.__kernel_sock_timeval_tv_usec_get(swigCPtr, this);
  }

  public __kernel_sock_timeval() {
    this(arblibJNI.new___kernel_sock_timeval(), true);
  }

}
