/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __kernel_fsid_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __kernel_fsid_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__kernel_fsid_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___kernel_fsid_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVal(SWIGTYPE_p_int value) {
    arblibJNI.__kernel_fsid_t_val_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getVal() {
    long cPtr = arblibJNI.__kernel_fsid_t_val_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public __kernel_fsid_t() {
    this(arblibJNI.new___kernel_fsid_t(), true);
  }

}
