/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __locale_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __locale_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__locale_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___locale_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__locales(SWIGTYPE_p_p___locale_data value) {
    arblibJNI.__locale_struct___locales_set(swigCPtr, this, SWIGTYPE_p_p___locale_data.getCPtr(value));
  }

  public SWIGTYPE_p_p___locale_data get__locales() {
    long cPtr = arblibJNI.__locale_struct___locales_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p___locale_data(cPtr, false);
  }

  public void set__ctype_b(SWIGTYPE_p_unsigned_short value) {
    arblibJNI.__locale_struct___ctype_b_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short get__ctype_b() {
    long cPtr = arblibJNI.__locale_struct___ctype_b_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void set__ctype_tolower(SWIGTYPE_p_int value) {
    arblibJNI.__locale_struct___ctype_tolower_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int get__ctype_tolower() {
    long cPtr = arblibJNI.__locale_struct___ctype_tolower_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void set__ctype_toupper(SWIGTYPE_p_int value) {
    arblibJNI.__locale_struct___ctype_toupper_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int get__ctype_toupper() {
    long cPtr = arblibJNI.__locale_struct___ctype_toupper_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void set__names(SWIGTYPE_p_p_char value) {
    arblibJNI.__locale_struct___names_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char get__names() {
    long cPtr = arblibJNI.__locale_struct___names_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public __locale_struct() {
    this(arblibJNI.new___locale_struct(), true);
  }

}
