/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __mbstate_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __mbstate_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__mbstate_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___mbstate_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__count(int value) {
    arblibJNI.__mbstate_t___count_set(swigCPtr, this, value);
  }

  public int get__count() {
    return arblibJNI.__mbstate_t___count_get(swigCPtr, this);
  }

  public __mbstate_t() {
    this(arblibJNI.new___mbstate_t(), true);
  }

}
