/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __mpfr_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __mpfr_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__mpfr_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___mpfr_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_mpfr_prec(int value) {
    arblibJNI.__mpfr_struct__mpfr_prec_set(swigCPtr, this, value);
  }

  public int get_mpfr_prec() {
    return arblibJNI.__mpfr_struct__mpfr_prec_get(swigCPtr, this);
  }

  public void set_mpfr_sign(int value) {
    arblibJNI.__mpfr_struct__mpfr_sign_set(swigCPtr, this, value);
  }

  public int get_mpfr_sign() {
    return arblibJNI.__mpfr_struct__mpfr_sign_get(swigCPtr, this);
  }

  public void set_mpfr_exp(int value) {
    arblibJNI.__mpfr_struct__mpfr_exp_set(swigCPtr, this, value);
  }

  public int get_mpfr_exp() {
    return arblibJNI.__mpfr_struct__mpfr_exp_get(swigCPtr, this);
  }

  public void set_mpfr_d(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.__mpfr_struct__mpfr_d_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long get_mpfr_d() {
    long cPtr = arblibJNI.__mpfr_struct__mpfr_d_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public __mpfr_struct() {
    this(arblibJNI.new___mpfr_struct(), true);
  }

}
