/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __mpz_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __mpz_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__mpz_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___mpz_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_mp_alloc(int value) {
    arblibJNI.__mpz_struct__mp_alloc_set(swigCPtr, this, value);
  }

  public int get_mp_alloc() {
    return arblibJNI.__mpz_struct__mp_alloc_get(swigCPtr, this);
  }

  public void set_mp_size(int value) {
    arblibJNI.__mpz_struct__mp_size_set(swigCPtr, this, value);
  }

  public int get_mp_size() {
    return arblibJNI.__mpz_struct__mp_size_get(swigCPtr, this);
  }

  public void set_mp_d(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.__mpz_struct__mp_d_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long get_mp_d() {
    long cPtr = arblibJNI.__mpz_struct__mp_d_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public __mpz_struct() {
    this(arblibJNI.new___mpz_struct(), true);
  }

}
