/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __once_flag {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __once_flag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__once_flag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___once_flag(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__data(int value) {
    arblibJNI.__once_flag___data_set(swigCPtr, this, value);
  }

  public int get__data() {
    return arblibJNI.__once_flag___data_get(swigCPtr, this);
  }

  public __once_flag() {
    this(arblibJNI.new___once_flag(), true);
  }

}
