/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __pthread_slist_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __pthread_slist_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__pthread_slist_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___pthread_slist_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__next(__pthread_slist_t value) {
    arblibJNI.__pthread_slist_t___next_set(swigCPtr, this, __pthread_slist_t.getCPtr(value), value);
  }

  public __pthread_slist_t get__next() {
    long cPtr = arblibJNI.__pthread_slist_t___next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __pthread_slist_t(cPtr, false);
  }

  public __pthread_slist_t() {
    this(arblibJNI.new___pthread_slist_t(), true);
  }

}
