/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __pthread_cond_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __pthread_cond_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__pthread_cond_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___pthread_cond_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__wseq(java.math.BigInteger value) {
    arblibJNI.__pthread_cond_s___wseq_set(swigCPtr, this, value);
  }

  public java.math.BigInteger get__wseq() {
    return arblibJNI.__pthread_cond_s___wseq_get(swigCPtr, this);
  }

  public void set__g1_start(java.math.BigInteger value) {
    arblibJNI.__pthread_cond_s___g1_start_set(swigCPtr, this, value);
  }

  public java.math.BigInteger get__g1_start() {
    return arblibJNI.__pthread_cond_s___g1_start_get(swigCPtr, this);
  }

  public void set__g_refs(SWIGTYPE_p_unsigned_int value) {
    arblibJNI.__pthread_cond_s___g_refs_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int get__g_refs() {
    long cPtr = arblibJNI.__pthread_cond_s___g_refs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void set__g_size(SWIGTYPE_p_unsigned_int value) {
    arblibJNI.__pthread_cond_s___g_size_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int get__g_size() {
    long cPtr = arblibJNI.__pthread_cond_s___g_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void set__g1_orig_size(long value) {
    arblibJNI.__pthread_cond_s___g1_orig_size_set(swigCPtr, this, value);
  }

  public long get__g1_orig_size() {
    return arblibJNI.__pthread_cond_s___g1_orig_size_get(swigCPtr, this);
  }

  public void set__wrefs(long value) {
    arblibJNI.__pthread_cond_s___wrefs_set(swigCPtr, this, value);
  }

  public long get__wrefs() {
    return arblibJNI.__pthread_cond_s___wrefs_get(swigCPtr, this);
  }

  public void set__g_signals(SWIGTYPE_p_unsigned_int value) {
    arblibJNI.__pthread_cond_s___g_signals_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int get__g_signals() {
    long cPtr = arblibJNI.__pthread_cond_s___g_signals_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public __pthread_cond_s() {
    this(arblibJNI.new___pthread_cond_s(), true);
  }

}
