/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __pthread_cleanup_frame {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __pthread_cleanup_frame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__pthread_cleanup_frame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___pthread_cleanup_frame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__cancel_routine(SWIGTYPE_p_f_p_void__void value) {
    arblibJNI.__pthread_cleanup_frame___cancel_routine_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void get__cancel_routine() {
    long cPtr = arblibJNI.__pthread_cleanup_frame___cancel_routine_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void set__cancel_arg(SWIGTYPE_p_void value) {
    arblibJNI.__pthread_cleanup_frame___cancel_arg_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void get__cancel_arg() {
    long cPtr = arblibJNI.__pthread_cleanup_frame___cancel_arg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void set__do_it(int value) {
    arblibJNI.__pthread_cleanup_frame___do_it_set(swigCPtr, this, value);
  }

  public int get__do_it() {
    return arblibJNI.__pthread_cleanup_frame___do_it_get(swigCPtr, this);
  }

  public void set__cancel_type(int value) {
    arblibJNI.__pthread_cleanup_frame___cancel_type_set(swigCPtr, this, value);
  }

  public int get__cancel_type() {
    return arblibJNI.__pthread_cleanup_frame___cancel_type_get(swigCPtr, this);
  }

  public __pthread_cleanup_frame() {
    this(arblibJNI.new___pthread_cleanup_frame(), true);
  }

}
