/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class __pthread_unwind_buf_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected __pthread_unwind_buf_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(__pthread_unwind_buf_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete___pthread_unwind_buf_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__pad(SWIGTYPE_p_p_void value) {
    arblibJNI.__pthread_unwind_buf_t___pad_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void get__pad() {
    long cPtr = arblibJNI.__pthread_unwind_buf_t___pad_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public __pthread_unwind_buf_t() {
    this(arblibJNI.new___pthread_unwind_buf_t(), true);
  }

}
