/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class _fmpq_ball_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _fmpq_ball_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_fmpq_ball_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete__fmpq_ball_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLeft_num(SWIGTYPE_p_long value) {
    arblibJNI._fmpq_ball_struct_left_num_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getLeft_num() {
    long cPtr = arblibJNI._fmpq_ball_struct_left_num_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setLeft_den(SWIGTYPE_p_long value) {
    arblibJNI._fmpq_ball_struct_left_den_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getLeft_den() {
    long cPtr = arblibJNI._fmpq_ball_struct_left_den_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setRight_num(SWIGTYPE_p_long value) {
    arblibJNI._fmpq_ball_struct_right_num_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getRight_num() {
    long cPtr = arblibJNI._fmpq_ball_struct_right_num_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setRight_den(SWIGTYPE_p_long value) {
    arblibJNI._fmpq_ball_struct_right_den_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getRight_den() {
    long cPtr = arblibJNI._fmpq_ball_struct_right_den_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setExact(int value) {
    arblibJNI._fmpq_ball_struct_exact_set(swigCPtr, this, value);
  }

  public int getExact() {
    return arblibJNI._fmpq_ball_struct_exact_get(swigCPtr, this);
  }

  public _fmpq_ball_struct() {
    this(arblibJNI.new__fmpq_ball_struct(), true);
  }

}
