/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class _fmpq_cfrac_list_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _fmpq_cfrac_list_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_fmpq_cfrac_list_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete__fmpq_cfrac_list_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setArray(SWIGTYPE_p_long value) {
    arblibJNI._fmpq_cfrac_list_struct_array_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getArray() {
    long cPtr = arblibJNI._fmpq_cfrac_list_struct_array_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setLength(int value) {
    arblibJNI._fmpq_cfrac_list_struct_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return arblibJNI._fmpq_cfrac_list_struct_length_get(swigCPtr, this);
  }

  public void setAlloc(int value) {
    arblibJNI._fmpq_cfrac_list_struct_alloc_set(swigCPtr, this, value);
  }

  public int getAlloc() {
    return arblibJNI._fmpq_cfrac_list_struct_alloc_get(swigCPtr, this);
  }

  public void setLimit(int value) {
    arblibJNI._fmpq_cfrac_list_struct_limit_set(swigCPtr, this, value);
  }

  public int getLimit() {
    return arblibJNI._fmpq_cfrac_list_struct_limit_get(swigCPtr, this);
  }

  public void setAlt_sum(SWIGTYPE_p_long value) {
    arblibJNI._fmpq_cfrac_list_struct_alt_sum_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getAlt_sum() {
    long cPtr = arblibJNI._fmpq_cfrac_list_struct_alt_sum_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setWant_alt_sum(int value) {
    arblibJNI._fmpq_cfrac_list_struct_want_alt_sum_set(swigCPtr, this, value);
  }

  public int getWant_alt_sum() {
    return arblibJNI._fmpq_cfrac_list_struct_want_alt_sum_get(swigCPtr, this);
  }

  public _fmpq_cfrac_list_struct() {
    this(arblibJNI.new__fmpq_cfrac_list_struct(), true);
  }

}
