/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class acb_dirichlet_hurwitz_precomp_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected acb_dirichlet_hurwitz_precomp_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(acb_dirichlet_hurwitz_precomp_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_acb_dirichlet_hurwitz_precomp_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setS(acb_struct value) {
    arblibJNI.acb_dirichlet_hurwitz_precomp_struct_s_set(swigCPtr, this, acb_struct.getCPtr(value), value);
  }

  public acb_struct getS() {
    long cPtr = arblibJNI.acb_dirichlet_hurwitz_precomp_struct_s_get(swigCPtr, this);
    return (cPtr == 0) ? null : new acb_struct(cPtr, false);
  }

  public void setErr(mag_struct value) {
    arblibJNI.acb_dirichlet_hurwitz_precomp_struct_err_set(swigCPtr, this, mag_struct.getCPtr(value), value);
  }

  public mag_struct getErr() {
    long cPtr = arblibJNI.acb_dirichlet_hurwitz_precomp_struct_err_get(swigCPtr, this);
    return (cPtr == 0) ? null : new mag_struct(cPtr, false);
  }

  public void setCoeffs(acb_struct value) {
    arblibJNI.acb_dirichlet_hurwitz_precomp_struct_coeffs_set(swigCPtr, this, acb_struct.getCPtr(value), value);
  }

  public acb_struct getCoeffs() {
    long cPtr = arblibJNI.acb_dirichlet_hurwitz_precomp_struct_coeffs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new acb_struct(cPtr, false);
  }

  public void setDeflate(int value) {
    arblibJNI.acb_dirichlet_hurwitz_precomp_struct_deflate_set(swigCPtr, this, value);
  }

  public int getDeflate() {
    return arblibJNI.acb_dirichlet_hurwitz_precomp_struct_deflate_get(swigCPtr, this);
  }

  public void setA(int value) {
    arblibJNI.acb_dirichlet_hurwitz_precomp_struct_A_set(swigCPtr, this, value);
  }

  public int getA() {
    return arblibJNI.acb_dirichlet_hurwitz_precomp_struct_A_get(swigCPtr, this);
  }

  public void setN(int value) {
    arblibJNI.acb_dirichlet_hurwitz_precomp_struct_N_set(swigCPtr, this, value);
  }

  public int getN() {
    return arblibJNI.acb_dirichlet_hurwitz_precomp_struct_N_get(swigCPtr, this);
  }

  public void setK(int value) {
    arblibJNI.acb_dirichlet_hurwitz_precomp_struct_K_set(swigCPtr, this, value);
  }

  public int getK() {
    return arblibJNI.acb_dirichlet_hurwitz_precomp_struct_K_get(swigCPtr, this);
  }

  public acb_dirichlet_hurwitz_precomp_struct() {
    this(arblibJNI.new_acb_dirichlet_hurwitz_precomp_struct(), true);
  }

}
