/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class acb_dirichlet_roots_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected acb_dirichlet_roots_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(acb_dirichlet_roots_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_acb_dirichlet_roots_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrder(long value) {
    arblibJNI.acb_dirichlet_roots_struct_order_set(swigCPtr, this, value);
  }

  public long getOrder() {
    return arblibJNI.acb_dirichlet_roots_struct_order_get(swigCPtr, this);
  }

  public void setReduced_order(long value) {
    arblibJNI.acb_dirichlet_roots_struct_reduced_order_set(swigCPtr, this, value);
  }

  public long getReduced_order() {
    return arblibJNI.acb_dirichlet_roots_struct_reduced_order_get(swigCPtr, this);
  }

  public void setZ(acb_struct value) {
    arblibJNI.acb_dirichlet_roots_struct_z_set(swigCPtr, this, acb_struct.getCPtr(value), value);
  }

  public acb_struct getZ() {
    long cPtr = arblibJNI.acb_dirichlet_roots_struct_z_get(swigCPtr, this);
    return (cPtr == 0) ? null : new acb_struct(cPtr, false);
  }

  public void setSize(int value) {
    arblibJNI.acb_dirichlet_roots_struct_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return arblibJNI.acb_dirichlet_roots_struct_size_get(swigCPtr, this);
  }

  public void setDepth(int value) {
    arblibJNI.acb_dirichlet_roots_struct_depth_set(swigCPtr, this, value);
  }

  public int getDepth() {
    return arblibJNI.acb_dirichlet_roots_struct_depth_get(swigCPtr, this);
  }

  public void setZptr(SWIGTYPE_p_p_acb_struct value) {
    arblibJNI.acb_dirichlet_roots_struct_Zptr_set(swigCPtr, this, SWIGTYPE_p_p_acb_struct.getCPtr(value));
  }

  public SWIGTYPE_p_p_acb_struct getZptr() {
    long cPtr = arblibJNI.acb_dirichlet_roots_struct_Zptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_acb_struct(cPtr, false);
  }

  public void setUse_pow(int value) {
    arblibJNI.acb_dirichlet_roots_struct_use_pow_set(swigCPtr, this, value);
  }

  public int getUse_pow() {
    return arblibJNI.acb_dirichlet_roots_struct_use_pow_get(swigCPtr, this);
  }

  public acb_dirichlet_roots_struct() {
    this(arblibJNI.new_acb_dirichlet_roots_struct(), true);
  }

}
