/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class acb_poly_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected acb_poly_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(acb_poly_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_acb_poly_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCoeffs(acb_struct value) {
    arblibJNI.acb_poly_struct_coeffs_set(swigCPtr, this, acb_struct.getCPtr(value), value);
  }

  public acb_struct getCoeffs() {
    long cPtr = arblibJNI.acb_poly_struct_coeffs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new acb_struct(cPtr, false);
  }

  public void setLength(int value) {
    arblibJNI.acb_poly_struct_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return arblibJNI.acb_poly_struct_length_get(swigCPtr, this);
  }

  public void setAlloc(int value) {
    arblibJNI.acb_poly_struct_alloc_set(swigCPtr, this, value);
  }

  public int getAlloc() {
    return arblibJNI.acb_poly_struct_alloc_get(swigCPtr, this);
  }

  public acb_poly_struct() {
    this(arblibJNI.new_acb_poly_struct(), true);
  }

}
