/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class acb_dirichlet_platt_c_precomp_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected acb_dirichlet_platt_c_precomp_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(acb_dirichlet_platt_c_precomp_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_acb_dirichlet_platt_c_precomp_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLen(SWIGTYPE_p_slong value) {
    arblibJNI.acb_dirichlet_platt_c_precomp_struct_len_set(swigCPtr, this, SWIGTYPE_p_slong.getCPtr(value));
  }

  public SWIGTYPE_p_slong getLen() {
    return new SWIGTYPE_p_slong(arblibJNI.acb_dirichlet_platt_c_precomp_struct_len_get(swigCPtr, this), true);
  }

  public void setP(arb_struct value) {
    arblibJNI.acb_dirichlet_platt_c_precomp_struct_p_set(swigCPtr, this, arb_struct.getCPtr(value), value);
  }

  public arb_struct getP() {
    long cPtr = arblibJNI.acb_dirichlet_platt_c_precomp_struct_p_get(swigCPtr, this);
    return (cPtr == 0) ? null : new arb_struct(cPtr, false);
  }

  public void setXa(arb_struct value) {
    arblibJNI.acb_dirichlet_platt_c_precomp_struct_Xa_set(swigCPtr, this, arb_struct.getCPtr(value), value);
  }

  public arb_struct getXa() {
    long cPtr = arblibJNI.acb_dirichlet_platt_c_precomp_struct_Xa_get(swigCPtr, this);
    return (cPtr == 0) ? null : new arb_struct(cPtr, false);
  }

  public void setXb(arb_struct value) {
    arblibJNI.acb_dirichlet_platt_c_precomp_struct_Xb_set(swigCPtr, this, arb_struct.getCPtr(value), value);
  }

  public arb_struct getXb() {
    long cPtr = arblibJNI.acb_dirichlet_platt_c_precomp_struct_Xb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new arb_struct(cPtr, false);
  }

  public acb_dirichlet_platt_c_precomp_struct() {
    this(arblibJNI.new_acb_dirichlet_platt_c_precomp_struct(), true);
  }

}
