/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class acb_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected acb_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(acb_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_acb_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReal(SWIGTYPE_p_arb_struct value) {
    arblibJNI.acb_struct_real_set(swigCPtr, this, SWIGTYPE_p_arb_struct.getCPtr(value));
  }

  public SWIGTYPE_p_arb_struct getReal() {
    return new SWIGTYPE_p_arb_struct(arblibJNI.acb_struct_real_get(swigCPtr, this), true);
  }

  public void setImag(SWIGTYPE_p_arb_struct value) {
    arblibJNI.acb_struct_imag_set(swigCPtr, this, SWIGTYPE_p_arb_struct.getCPtr(value));
  }

  public SWIGTYPE_p_arb_struct getImag() {
    return new SWIGTYPE_p_arb_struct(arblibJNI.acb_struct_imag_get(swigCPtr, this), true);
  }

  public acb_struct() {
    this(arblibJNI.new_acb_struct(), true);
  }

}
