/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class apow_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected apow_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(apow_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_apow_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setK(long value) {
    arblibJNI.apow_t_k_set(swigCPtr, this, value);
  }

  public long getK() {
    return arblibJNI.apow_t_k_get(swigCPtr, this);
  }

  public void setAk(long value) {
    arblibJNI.apow_t_ak_set(swigCPtr, this, value);
  }

  public long getAk() {
    return arblibJNI.apow_t_ak_get(swigCPtr, this);
  }

  public apow_t() {
    this(arblibJNI.new_apow_t(), true);
  }

}
