/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class arb_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected arb_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(arb_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_arb_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMid(SWIGTYPE_p_arf_struct value) {
    arblibJNI.arb_struct_mid_set(swigCPtr, this, SWIGTYPE_p_arf_struct.getCPtr(value));
  }

  public SWIGTYPE_p_arf_struct getMid() {
    return new SWIGTYPE_p_arf_struct(arblibJNI.arb_struct_mid_get(swigCPtr, this), true);
  }

  public void setRad(SWIGTYPE_p_mag_struct value) {
    arblibJNI.arb_struct_rad_set(swigCPtr, this, SWIGTYPE_p_mag_struct.getCPtr(value));
  }

  public SWIGTYPE_p_mag_struct getRad() {
    return new SWIGTYPE_p_mag_struct(arblibJNI.arb_struct_rad_get(swigCPtr, this), true);
  }

  public arb_struct() {
    this(arblibJNI.new_arb_struct(), true);
  }

}
