/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class arblib {
  public static void color_function(double[] R, double[] G, double[] B, acb_struct z, int mode) {
    arblibJNI.color_function(R, G, B, acb_struct.getCPtr(z), z, mode);
  }

  public static void arf_init(arf_struct x) {
    arblibJNI.arf_init(arf_struct.getCPtr(x), x);
  }

  public static void acb_init(acb_struct x) {
    arblibJNI.acb_init(acb_struct.getCPtr(x), x);
  }

  public static void arb_init(arb_struct x) {
    arblibJNI.arb_init(arb_struct.getCPtr(x), x);
  }

  public static void acb_set_d(acb_struct z, double c) {
    arblibJNI.acb_set_d(acb_struct.getCPtr(z), z, c);
  }

  public static void acb_dirichlet_hardy_z(acb_struct res, acb_struct t, dirichlet_group_struct G, dirichlet_char_struct chi, int len, int prec) {
    arblibJNI.acb_dirichlet_hardy_z(acb_struct.getCPtr(res), res, acb_struct.getCPtr(t), t, dirichlet_group_struct.getCPtr(G), G, dirichlet_char_struct.getCPtr(chi), chi, len, prec);
  }

  public static void acb_print(acb_struct x) {
    arblibJNI.acb_print(acb_struct.getCPtr(x), x);
  }

  public static String arb_get_str(arb_struct x, int n, long flags) {
    return arblibJNI.arb_get_str(arb_struct.getCPtr(x), x, n, flags);
  }

  public static double arf_get_d(arf_struct x, int rnd) {
    return arblibJNI.arf_get_d(arf_struct.getCPtr(x), x, rnd);
  }

  public static void arf_set_d(arf_struct x, double v) {
    arblibJNI.arf_set_d(arf_struct.getCPtr(x), x, v);
  }

  public static int arf_sub(arf_struct z, arf_struct x, arf_struct y, int prec, int rnd) {
    return arblibJNI.arf_sub(arf_struct.getCPtr(z), z, arf_struct.getCPtr(x), x, arf_struct.getCPtr(y), y, prec, rnd);
  }

  public static void arb_mul_ui(arb_struct z, arb_struct x, long y, int prec) {
    arblibJNI.arb_mul_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, y, prec);
  }

  public static int arf_mul_ui(arf_struct z, arf_struct x, long y, int prec, int rnd) {
    return arblibJNI.arf_mul_ui(arf_struct.getCPtr(z), z, arf_struct.getCPtr(x), x, y, prec, rnd);
  }

  public static int arf_div_ui(arf_struct z, arf_struct x, long y, int prec, int rnd) {
    return arblibJNI.arf_div_ui(arf_struct.getCPtr(z), z, arf_struct.getCPtr(x), x, y, prec, rnd);
  }

  public static int arf_add(arf_struct z, arf_struct x, arf_struct y, int prec, int rnd) {
    return arblibJNI.arf_add(arf_struct.getCPtr(z), z, arf_struct.getCPtr(x), x, arf_struct.getCPtr(y), y, prec, rnd);
  }

  public static int acb_rel_accuracy_bits(acb_struct x) {
    return arblibJNI.acb_rel_accuracy_bits(acb_struct.getCPtr(x), x);
  }

  public static void acb_pow_ui(acb_struct y, acb_struct b, long e, int prec) {
    arblibJNI.acb_pow_ui(acb_struct.getCPtr(y), y, acb_struct.getCPtr(b), b, e, prec);
  }

  public static void acb_add_ui(acb_struct z, acb_struct x, long c, int prec) {
    arblibJNI.acb_add_ui(acb_struct.getCPtr(z), z, acb_struct.getCPtr(x), x, c, prec);
  }

  public static void acb_log(acb_struct r, acb_struct z, int prec) {
    arblibJNI.acb_log(acb_struct.getCPtr(r), r, acb_struct.getCPtr(z), z, prec);
  }

  public static void acb_tanh(acb_struct y, acb_struct x, int prec) {
    arblibJNI.acb_tanh(acb_struct.getCPtr(y), y, acb_struct.getCPtr(x), x, prec);
  }

  public static void arb_set_d(arb_struct x, double y) {
    arblibJNI.arb_set_d(arb_struct.getCPtr(x), x, y);
  }

  public static void acb_dirichlet_hurwitz(acb_struct res, acb_struct s, acb_struct a, int prec) {
    arblibJNI.acb_dirichlet_hurwitz(acb_struct.getCPtr(res), res, acb_struct.getCPtr(s), s, acb_struct.getCPtr(a), a, prec);
  }

}
