/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class arblibJNI {
  public final static native void acb_struct_real_set(long jarg1, acb_struct jarg1_, long jarg2, arb_struct jarg2_);
  public final static native long acb_struct_real_get(long jarg1, acb_struct jarg1_);
  public final static native void acb_struct_imag_set(long jarg1, acb_struct jarg1_, long jarg2, arb_struct jarg2_);
  public final static native long acb_struct_imag_get(long jarg1, acb_struct jarg1_);
  public final static native long new_acb_struct();
  public final static native void delete_acb_struct(long jarg1);
  public final static native void dirichlet_group_struct_q_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_group_struct_q_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_q_even_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_group_struct_q_even_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_mod_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_group_struct_mod_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_rad_q_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_group_struct_rad_q_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_phi_q_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_group_struct_phi_q_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_neven_set(long jarg1, dirichlet_group_struct jarg1_, int jarg2);
  public final static native int dirichlet_group_struct_neven_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_num_set(long jarg1, dirichlet_group_struct jarg1_, int jarg2);
  public final static native int dirichlet_group_struct_num_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_expo_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_group_struct_expo_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_P_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2, dirichlet_prime_group_struct jarg2_);
  public final static native long dirichlet_group_struct_P_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_generators_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_group_struct_generators_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native void dirichlet_group_struct_PHI_set(long jarg1, dirichlet_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_group_struct_PHI_get(long jarg1, dirichlet_group_struct jarg1_);
  public final static native long new_dirichlet_group_struct();
  public final static native void delete_dirichlet_group_struct(long jarg1);
  public final static native void dirichlet_char_struct_n_set(long jarg1, dirichlet_char_struct jarg1_, long jarg2);
  public final static native long dirichlet_char_struct_n_get(long jarg1, dirichlet_char_struct jarg1_);
  public final static native void dirichlet_char_struct_log_set(long jarg1, dirichlet_char_struct jarg1_, long jarg2);
  public final static native long dirichlet_char_struct_log_get(long jarg1, dirichlet_char_struct jarg1_);
  public final static native long new_dirichlet_char_struct();
  public final static native void delete_dirichlet_char_struct(long jarg1);
  public final static native void dirichlet_prime_group_struct_p_set(long jarg1, dirichlet_prime_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_prime_group_struct_p_get(long jarg1, dirichlet_prime_group_struct jarg1_);
  public final static native void dirichlet_prime_group_struct_e_set(long jarg1, dirichlet_prime_group_struct jarg1_, int jarg2);
  public final static native int dirichlet_prime_group_struct_e_get(long jarg1, dirichlet_prime_group_struct jarg1_);
  public final static native void dirichlet_prime_group_struct_pe_set(long jarg1, dirichlet_prime_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_prime_group_struct_pe_get(long jarg1, dirichlet_prime_group_struct jarg1_);
  public final static native void dirichlet_prime_group_struct_phi_set(long jarg1, dirichlet_prime_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_prime_group_struct_phi_get(long jarg1, dirichlet_prime_group_struct jarg1_);
  public final static native void dirichlet_prime_group_struct_g_set(long jarg1, dirichlet_prime_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_prime_group_struct_g_get(long jarg1, dirichlet_prime_group_struct jarg1_);
  public final static native void dirichlet_prime_group_struct_dlog_set(long jarg1, dirichlet_prime_group_struct jarg1_, long jarg2);
  public final static native long dirichlet_prime_group_struct_dlog_get(long jarg1, dirichlet_prime_group_struct jarg1_);
  public final static native long new_dirichlet_prime_group_struct();
  public final static native void delete_dirichlet_prime_group_struct(long jarg1);
  public final static native void arb_struct_mid_set(long jarg1, arb_struct jarg1_, long jarg2, arf_struct jarg2_);
  public final static native long arb_struct_mid_get(long jarg1, arb_struct jarg1_);
  public final static native void arb_struct_rad_set(long jarg1, arb_struct jarg1_, long jarg2);
  public final static native long arb_struct_rad_get(long jarg1, arb_struct jarg1_);
  public final static native long new_arb_struct();
  public final static native void delete_arb_struct(long jarg1);
  public final static native void mantissa_noptr_struct_d_set(long jarg1, mantissa_noptr_struct jarg1_, long jarg2);
  public final static native long mantissa_noptr_struct_d_get(long jarg1, mantissa_noptr_struct jarg1_);
  public final static native long new_mantissa_noptr_struct();
  public final static native void delete_mantissa_noptr_struct(long jarg1);
  public final static native void mantissa_ptr_struct_alloc_set(long jarg1, mantissa_ptr_struct jarg1_, long jarg2);
  public final static native long mantissa_ptr_struct_alloc_get(long jarg1, mantissa_ptr_struct jarg1_);
  public final static native void mantissa_ptr_struct_d_set(long jarg1, mantissa_ptr_struct jarg1_, long jarg2);
  public final static native long mantissa_ptr_struct_d_get(long jarg1, mantissa_ptr_struct jarg1_);
  public final static native long new_mantissa_ptr_struct();
  public final static native void delete_mantissa_ptr_struct(long jarg1);
  public final static native void mantissa_struct_noptr_set(long jarg1, mantissa_struct jarg1_, long jarg2, mantissa_noptr_struct jarg2_);
  public final static native long mantissa_struct_noptr_get(long jarg1, mantissa_struct jarg1_);
  public final static native void mantissa_struct_ptr_set(long jarg1, mantissa_struct jarg1_, long jarg2, mantissa_ptr_struct jarg2_);
  public final static native long mantissa_struct_ptr_get(long jarg1, mantissa_struct jarg1_);
  public final static native long new_mantissa_struct();
  public final static native void delete_mantissa_struct(long jarg1);
  public final static native void arf_struct_exp_set(long jarg1, arf_struct jarg1_, long jarg2);
  public final static native long arf_struct_exp_get(long jarg1, arf_struct jarg1_);
  public final static native void arf_struct_size_set(long jarg1, arf_struct jarg1_, long jarg2);
  public final static native long arf_struct_size_get(long jarg1, arf_struct jarg1_);
  public final static native void arf_struct_d_set(long jarg1, arf_struct jarg1_, long jarg2, mantissa_struct jarg2_);
  public final static native long arf_struct_d_get(long jarg1, arf_struct jarg1_);
  public final static native long new_arf_struct();
  public final static native void delete_arf_struct(long jarg1);
  public final static native void acb_set_d(long jarg1, acb_struct jarg1_, double jarg2);
  public final static native void acb_dirichlet_hardy_z(long jarg1, acb_struct jarg1_, long jarg2, acb_struct jarg2_, long jarg3, dirichlet_group_struct jarg3_, long jarg4, dirichlet_char_struct jarg4_, int jarg5, int jarg6);
  public final static native void acb_print(long jarg1, acb_struct jarg1_);
}
