/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public interface arblibConstants {
  public final static int __ARB_VERSION = arblibJNI.__ARB_VERSION_get();
  public final static int __ARB_VERSION_MINOR = arblibJNI.__ARB_VERSION_MINOR_get();
  public final static int __ARB_VERSION_PATCHLEVEL = arblibJNI.__ARB_VERSION_PATCHLEVEL_get();
  public final static String ARB_VERSION = arblibJNI.ARB_VERSION_get();
  public final static int __ARB_RELEASE = arblibJNI.__ARB_RELEASE_get();
  public final static int ARB_ATAN_TAB1_BITS = arblibJNI.ARB_ATAN_TAB1_BITS_get();
  public final static int ARB_ATAN_TAB1_PREC = arblibJNI.ARB_ATAN_TAB1_PREC_get();
  public final static int ARB_ATAN_TAB21_BITS = arblibJNI.ARB_ATAN_TAB21_BITS_get();
  public final static int ARB_ATAN_TAB22_BITS = arblibJNI.ARB_ATAN_TAB22_BITS_get();
  public final static int ARB_ATAN_TAB2_PREC = arblibJNI.ARB_ATAN_TAB2_PREC_get();
  public final static int ARB_LOG_TAB11_BITS = arblibJNI.ARB_LOG_TAB11_BITS_get();
  public final static int ARB_LOG_TAB12_BITS = arblibJNI.ARB_LOG_TAB12_BITS_get();
  public final static int ARB_LOG_TAB1_PREC = arblibJNI.ARB_LOG_TAB1_PREC_get();
  public final static int ARB_LOG_TAB21_BITS = arblibJNI.ARB_LOG_TAB21_BITS_get();
  public final static int ARB_LOG_TAB22_BITS = arblibJNI.ARB_LOG_TAB22_BITS_get();
  public final static int ARB_LOG_TAB2_PREC = arblibJNI.ARB_LOG_TAB2_PREC_get();
  public final static int ARB_EXP_TAB1_NUM = arblibJNI.ARB_EXP_TAB1_NUM_get();
  public final static int ARB_EXP_TAB1_BITS = arblibJNI.ARB_EXP_TAB1_BITS_get();
  public final static int ARB_EXP_TAB1_PREC = arblibJNI.ARB_EXP_TAB1_PREC_get();
  public final static int ARB_EXP_TAB21_NUM = arblibJNI.ARB_EXP_TAB21_NUM_get();
  public final static int ARB_EXP_TAB21_BITS = arblibJNI.ARB_EXP_TAB21_BITS_get();
  public final static int ARB_EXP_TAB22_BITS = arblibJNI.ARB_EXP_TAB22_BITS_get();
  public final static int ARB_EXP_TAB2_PREC = arblibJNI.ARB_EXP_TAB2_PREC_get();
  public final static int ARB_SIN_COS_TAB1_NUM = arblibJNI.ARB_SIN_COS_TAB1_NUM_get();
  public final static int ARB_SIN_COS_TAB1_BITS = arblibJNI.ARB_SIN_COS_TAB1_BITS_get();
  public final static int ARB_SIN_COS_TAB1_PREC = arblibJNI.ARB_SIN_COS_TAB1_PREC_get();
  public final static int ARB_SIN_COS_TAB21_NUM = arblibJNI.ARB_SIN_COS_TAB21_NUM_get();
  public final static int ARB_SIN_COS_TAB21_BITS = arblibJNI.ARB_SIN_COS_TAB21_BITS_get();
  public final static int ARB_SIN_COS_TAB22_BITS = arblibJNI.ARB_SIN_COS_TAB22_BITS_get();
  public final static int ARB_SIN_COS_TAB2_PREC = arblibJNI.ARB_SIN_COS_TAB2_PREC_get();
  public final static int ACB_LAMBERTW_LEFT = arblibJNI.ACB_LAMBERTW_LEFT_get();
  public final static int ACB_LAMBERTW_MIDDLE = arblibJNI.ACB_LAMBERTW_MIDDLE_get();
  public final static int MAX_FACTORS = arblibJNI.MAX_FACTORS_get();
}
