/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public interface arblibConstants {
  public final static int MPFR_VERSION_MAJOR = arblibJNI.MPFR_VERSION_MAJOR_get();
  public final static int MPFR_VERSION_MINOR = arblibJNI.MPFR_VERSION_MINOR_get();
  public final static int MPFR_VERSION_PATCHLEVEL = arblibJNI.MPFR_VERSION_PATCHLEVEL_get();
  public final static String MPFR_VERSION_STRING = arblibJNI.MPFR_VERSION_STRING_get();
  public final static int MPFR_VERSION = arblibJNI.MPFR_VERSION_get();
  public final static int MPFR_FLAGS_UNDERFLOW = arblibJNI.MPFR_FLAGS_UNDERFLOW_get();
  public final static int MPFR_FLAGS_OVERFLOW = arblibJNI.MPFR_FLAGS_OVERFLOW_get();
  public final static int MPFR_FLAGS_NAN = arblibJNI.MPFR_FLAGS_NAN_get();
  public final static int MPFR_FLAGS_INEXACT = arblibJNI.MPFR_FLAGS_INEXACT_get();
  public final static int MPFR_FLAGS_ERANGE = arblibJNI.MPFR_FLAGS_ERANGE_get();
  public final static int MPFR_FLAGS_DIVBY0 = arblibJNI.MPFR_FLAGS_DIVBY0_get();
  public final static int MPFR_FLAGS_ALL = arblibJNI.MPFR_FLAGS_ALL_get();
  public final static int _MPFR_PREC_FORMAT = arblibJNI._MPFR_PREC_FORMAT_get();
  public final static int _MPFR_EXP_FORMAT = arblibJNI._MPFR_EXP_FORMAT_get();
  public final static int MPFR_PREC_MIN = arblibJNI.MPFR_PREC_MIN_get();
  public final static int MPFR_USE_C99_FEATURE = arblibJNI.MPFR_USE_C99_FEATURE_get();
  public final static int __GMP_HAVE_HOST_CPU_FAMILY_power = arblibJNI.__GMP_HAVE_HOST_CPU_FAMILY_power_get();
  public final static int __GMP_HAVE_HOST_CPU_FAMILY_powerpc = arblibJNI.__GMP_HAVE_HOST_CPU_FAMILY_powerpc_get();
  public final static int GMP_LIMB_BITS = arblibJNI.GMP_LIMB_BITS_get();
  public final static int GMP_NAIL_BITS = arblibJNI.GMP_NAIL_BITS_get();
  public final static int GMP_NUMB_BITS = arblibJNI.GMP_NUMB_BITS_get();
  public final static int __GNU_MP__ = arblibJNI.__GNU_MP___get();
  public final static int __GMP_LIBGMP_DLL = arblibJNI.__GMP_LIBGMP_DLL_get();
  public final static int __GMP_MP_SIZE_T_INT = arblibJNI.__GMP_MP_SIZE_T_INT_get();
  public final static int __GMP_INLINE_PROTOTYPES = arblibJNI.__GMP_INLINE_PROTOTYPES_get();
  public final static int GMP_ERROR_NONE = arblibJNI.GMP_ERROR_NONE_get();
  public final static int GMP_ERROR_UNSUPPORTED_ARGUMENT = arblibJNI.GMP_ERROR_UNSUPPORTED_ARGUMENT_get();
  public final static int GMP_ERROR_DIVISION_BY_ZERO = arblibJNI.GMP_ERROR_DIVISION_BY_ZERO_get();
  public final static int GMP_ERROR_SQRT_OF_NEGATIVE = arblibJNI.GMP_ERROR_SQRT_OF_NEGATIVE_get();
  public final static int GMP_ERROR_INVALID_ARGUMENT = arblibJNI.GMP_ERROR_INVALID_ARGUMENT_get();

  public final static String __GMP_CC = arblibJNI.__GMP_CC_get();
  public final static String __GMP_CFLAGS = arblibJNI.__GMP_CFLAGS_get();
  public final static int __GNU_MP_VERSION = arblibJNI.__GNU_MP_VERSION_get();
  public final static int __GNU_MP_VERSION_MINOR = arblibJNI.__GNU_MP_VERSION_MINOR_get();
  public final static int __GNU_MP_VERSION_PATCHLEVEL = arblibJNI.__GNU_MP_VERSION_PATCHLEVEL_get();
  public final static int __GNU_MP_RELEASE = arblibJNI.__GNU_MP_RELEASE_get();
  public final static int __FLINT_VERSION = arblibJNI.__FLINT_VERSION_get();
  public final static int __FLINT_VERSION_MINOR = arblibJNI.__FLINT_VERSION_MINOR_get();
  public final static int __FLINT_VERSION_PATCHLEVEL = arblibJNI.__FLINT_VERSION_PATCHLEVEL_get();
  public final static String FLINT_VERSION = arblibJNI.FLINT_VERSION_get();
  public final static int __FLINT_RELEASE = arblibJNI.__FLINT_RELEASE_get();
  public final static String WORD_FMT = arblibJNI.WORD_FMT_get();
  public final static String WORD_WIDTH_FMT = arblibJNI.WORD_WIDTH_FMT_get();
  public final static int FLINT_BITS = arblibJNI.FLINT_BITS_get();
  public final static int FLINT_D_BITS = arblibJNI.FLINT_D_BITS_get();
  public final static int FLINT64 = arblibJNI.FLINT64_get();
  public final static int ARF_RESULT_EXACT = arblibJNI.ARF_RESULT_EXACT_get();
  public final static int ARF_RESULT_INEXACT = arblibJNI.ARF_RESULT_INEXACT_get();
  public final static int ARF_EXP_ZERO = arblibJNI.ARF_EXP_ZERO_get();
  public final static int ARF_NOPTR_LIMBS = arblibJNI.ARF_NOPTR_LIMBS_get();
  public final static int MUL_MPFR_MIN_LIMBS = arblibJNI.MUL_MPFR_MIN_LIMBS_get();
  public final static int MUL_MPFR_MAX_LIMBS = arblibJNI.MUL_MPFR_MAX_LIMBS_get();
  public final static int ARF_MUL_STACK_ALLOC = arblibJNI.ARF_MUL_STACK_ALLOC_get();
  public final static int ARF_MUL_TLS_ALLOC = arblibJNI.ARF_MUL_TLS_ALLOC_get();
  public final static int ARF_ADD_STACK_ALLOC = arblibJNI.ARF_ADD_STACK_ALLOC_get();
  public final static int ARF_ADD_TLS_ALLOC = arblibJNI.ARF_ADD_TLS_ALLOC_get();
  public final static int __ARB_VERSION = arblibJNI.__ARB_VERSION_get();
  public final static int __ARB_VERSION_MINOR = arblibJNI.__ARB_VERSION_MINOR_get();
  public final static int __ARB_VERSION_PATCHLEVEL = arblibJNI.__ARB_VERSION_PATCHLEVEL_get();
  public final static String ARB_VERSION = arblibJNI.ARB_VERSION_get();
  public final static int __ARB_RELEASE = arblibJNI.__ARB_RELEASE_get();
  public final static long ARB_STR_MORE = arblibJNI.ARB_STR_MORE_get();
  public final static long ARB_STR_NO_RADIUS = arblibJNI.ARB_STR_NO_RADIUS_get();
  public final static long ARB_STR_CONDENSE = arblibJNI.ARB_STR_CONDENSE_get();
  public final static int ARB_ATAN_TAB1_BITS = arblibJNI.ARB_ATAN_TAB1_BITS_get();
  public final static int ARB_ATAN_TAB1_PREC = arblibJNI.ARB_ATAN_TAB1_PREC_get();
  public final static int ARB_ATAN_TAB1_LIMBS = arblibJNI.ARB_ATAN_TAB1_LIMBS_get();
  public final static int ARB_ATAN_TAB21_BITS = arblibJNI.ARB_ATAN_TAB21_BITS_get();
  public final static int ARB_ATAN_TAB22_BITS = arblibJNI.ARB_ATAN_TAB22_BITS_get();
  public final static int ARB_ATAN_TAB2_PREC = arblibJNI.ARB_ATAN_TAB2_PREC_get();
  public final static int ARB_ATAN_TAB2_LIMBS = arblibJNI.ARB_ATAN_TAB2_LIMBS_get();
  public final static int ARB_LOG_TAB11_BITS = arblibJNI.ARB_LOG_TAB11_BITS_get();
  public final static int ARB_LOG_TAB12_BITS = arblibJNI.ARB_LOG_TAB12_BITS_get();
  public final static int ARB_LOG_TAB1_PREC = arblibJNI.ARB_LOG_TAB1_PREC_get();
  public final static int ARB_LOG_TAB1_LIMBS = arblibJNI.ARB_LOG_TAB1_LIMBS_get();
  public final static int ARB_LOG_TAB21_BITS = arblibJNI.ARB_LOG_TAB21_BITS_get();
  public final static int ARB_LOG_TAB22_BITS = arblibJNI.ARB_LOG_TAB22_BITS_get();
  public final static int ARB_LOG_TAB2_PREC = arblibJNI.ARB_LOG_TAB2_PREC_get();
  public final static int ARB_LOG_TAB2_LIMBS = arblibJNI.ARB_LOG_TAB2_LIMBS_get();
  public final static int ARB_EXP_TAB1_NUM = arblibJNI.ARB_EXP_TAB1_NUM_get();
  public final static int ARB_EXP_TAB1_BITS = arblibJNI.ARB_EXP_TAB1_BITS_get();
  public final static int ARB_EXP_TAB1_PREC = arblibJNI.ARB_EXP_TAB1_PREC_get();
  public final static int ARB_EXP_TAB1_LIMBS = arblibJNI.ARB_EXP_TAB1_LIMBS_get();
  public final static int ARB_EXP_TAB21_NUM = arblibJNI.ARB_EXP_TAB21_NUM_get();
  public final static int ARB_EXP_TAB21_BITS = arblibJNI.ARB_EXP_TAB21_BITS_get();
  public final static int ARB_EXP_TAB22_BITS = arblibJNI.ARB_EXP_TAB22_BITS_get();
  public final static int ARB_EXP_TAB2_PREC = arblibJNI.ARB_EXP_TAB2_PREC_get();
  public final static int ARB_EXP_TAB2_LIMBS = arblibJNI.ARB_EXP_TAB2_LIMBS_get();
  public final static int ARB_SIN_COS_TAB1_NUM = arblibJNI.ARB_SIN_COS_TAB1_NUM_get();
  public final static int ARB_SIN_COS_TAB1_BITS = arblibJNI.ARB_SIN_COS_TAB1_BITS_get();
  public final static int ARB_SIN_COS_TAB1_PREC = arblibJNI.ARB_SIN_COS_TAB1_PREC_get();
  public final static int ARB_SIN_COS_TAB1_LIMBS = arblibJNI.ARB_SIN_COS_TAB1_LIMBS_get();
  public final static int ARB_SIN_COS_TAB21_NUM = arblibJNI.ARB_SIN_COS_TAB21_NUM_get();
  public final static int ARB_SIN_COS_TAB21_BITS = arblibJNI.ARB_SIN_COS_TAB21_BITS_get();
  public final static int ARB_SIN_COS_TAB22_BITS = arblibJNI.ARB_SIN_COS_TAB22_BITS_get();
  public final static int ARB_SIN_COS_TAB2_PREC = arblibJNI.ARB_SIN_COS_TAB2_PREC_get();
  public final static int ARB_SIN_COS_TAB2_LIMBS = arblibJNI.ARB_SIN_COS_TAB2_LIMBS_get();
  public final static int ARB_PI4_TAB_LIMBS = arblibJNI.ARB_PI4_TAB_LIMBS_get();
  public final static int ACB_LAMBERTW_LEFT = arblibJNI.ACB_LAMBERTW_LEFT_get();
  public final static int ACB_LAMBERTW_MIDDLE = arblibJNI.ACB_LAMBERTW_MIDDLE_get();
  public final static int MAX_FACTORS = arblibJNI.MAX_FACTORS_get();
}
