/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class arblib implements arblibConstants {
  public static void setArb_version(String value) {
    arblibJNI.arb_version_set(value);
  }

  public static String getArb_version() {
    return arblibJNI.arb_version_get();
  }

  public static double arb_test_multiplier() {
    return arblibJNI.arb_test_multiplier();
  }

  public static void arb_init(arb_struct x) {
    arblibJNI.arb_init(arb_struct.getCPtr(x), x);
  }

  public static void arb_clear(arb_struct x) {
    arblibJNI.arb_clear(arb_struct.getCPtr(x), x);
  }

  public static arb_struct _arb_vec_init(SWIGTYPE_p_slong n) {
    long cPtr = arblibJNI._arb_vec_init(SWIGTYPE_p_slong.getCPtr(n));
    return (cPtr == 0) ? null : new arb_struct(cPtr, false);
  }

  public static void _arb_vec_clear(arb_struct v, SWIGTYPE_p_slong n) {
    arblibJNI._arb_vec_clear(arb_struct.getCPtr(v), v, SWIGTYPE_p_slong.getCPtr(n));
  }

  public static SWIGTYPE_p_arf_ptr arb_mid_ptr(arb_struct z) {
    return new SWIGTYPE_p_arf_ptr(arblibJNI.arb_mid_ptr(arb_struct.getCPtr(z), z), true);
  }

  public static SWIGTYPE_p_mag_ptr arb_rad_ptr(arb_struct z) {
    return new SWIGTYPE_p_mag_ptr(arblibJNI.arb_rad_ptr(arb_struct.getCPtr(z), z), true);
  }

  public static int arb_is_exact(arb_struct x) {
    return arblibJNI.arb_is_exact(arb_struct.getCPtr(x), x);
  }

  public static int arb_equal(arb_struct x, arb_struct y) {
    return arblibJNI.arb_equal(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_equal_si(arb_struct x, SWIGTYPE_p_slong y) {
    return arblibJNI.arb_equal_si(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y));
  }

  public static int arb_eq(arb_struct x, arb_struct y) {
    return arblibJNI.arb_eq(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_ne(arb_struct x, arb_struct y) {
    return arblibJNI.arb_ne(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_lt(arb_struct x, arb_struct y) {
    return arblibJNI.arb_lt(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_le(arb_struct x, arb_struct y) {
    return arblibJNI.arb_le(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_gt(arb_struct x, arb_struct y) {
    return arblibJNI.arb_gt(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_ge(arb_struct x, arb_struct y) {
    return arblibJNI.arb_ge(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static void arb_zero(arb_struct x) {
    arblibJNI.arb_zero(arb_struct.getCPtr(x), x);
  }

  public static int arb_is_zero(arb_struct x) {
    return arblibJNI.arb_is_zero(arb_struct.getCPtr(x), x);
  }

  public static void arb_pos_inf(arb_struct x) {
    arblibJNI.arb_pos_inf(arb_struct.getCPtr(x), x);
  }

  public static void arb_neg_inf(arb_struct x) {
    arblibJNI.arb_neg_inf(arb_struct.getCPtr(x), x);
  }

  public static void arb_zero_pm_inf(arb_struct x) {
    arblibJNI.arb_zero_pm_inf(arb_struct.getCPtr(x), x);
  }

  public static void arb_zero_pm_one(arb_struct x) {
    arblibJNI.arb_zero_pm_one(arb_struct.getCPtr(x), x);
  }

  public static void arb_unit_interval(arb_struct x) {
    arblibJNI.arb_unit_interval(arb_struct.getCPtr(x), x);
  }

  public static void arb_indeterminate(arb_struct x) {
    arblibJNI.arb_indeterminate(arb_struct.getCPtr(x), x);
  }

  public static int arb_is_finite(arb_struct x) {
    return arblibJNI.arb_is_finite(arb_struct.getCPtr(x), x);
  }

  public static void arb_set(arb_struct x, arb_struct y) {
    arblibJNI.arb_set(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static void arb_swap(arb_struct x, arb_struct y) {
    arblibJNI.arb_swap(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static void arb_set_round(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_set_round(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_trim(arb_struct y, arb_struct x) {
    arblibJNI.arb_trim(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x);
  }

  public static void arb_neg(arb_struct y, arb_struct x) {
    arblibJNI.arb_neg(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x);
  }

  public static void arb_neg_round(arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_neg_round(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_abs(arb_struct y, arb_struct x) {
    arblibJNI.arb_abs(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x);
  }

  public static void arb_sgn(arb_struct res, arb_struct x) {
    arblibJNI.arb_sgn(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x);
  }

  public static int arb_sgn_nonzero(arb_struct x) {
    return arblibJNI.arb_sgn_nonzero(arb_struct.getCPtr(x), x);
  }

  public static void _arb_digits_round_inplace(String s, SWIGTYPE_p_flint_bitcnt_t shift, SWIGTYPE_p_fmpz_t error, SWIGTYPE_p_slong n, SWIGTYPE_p_arf_rnd_t rnd) {
    arblibJNI._arb_digits_round_inplace(s, SWIGTYPE_p_flint_bitcnt_t.getCPtr(shift), SWIGTYPE_p_fmpz_t.getCPtr(error), SWIGTYPE_p_slong.getCPtr(n), SWIGTYPE_p_arf_rnd_t.getCPtr(rnd));
  }

  public static int arb_set_str(arb_struct res, String inp, SWIGTYPE_p_slong prec) {
    return arblibJNI.arb_set_str(arb_struct.getCPtr(res), res, inp, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static String arb_get_str(arb_struct x, SWIGTYPE_p_slong n, SWIGTYPE_p_ulong flags) {
    return arblibJNI.arb_get_str(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(n), SWIGTYPE_p_ulong.getCPtr(flags));
  }

  public static void arb_set_arf(arb_struct x, SWIGTYPE_p_arf_t y) {
    arblibJNI.arb_set_arf(arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(y));
  }

  public static void arb_set_si(arb_struct x, SWIGTYPE_p_slong y) {
    arblibJNI.arb_set_si(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y));
  }

  public static void arb_set_ui(arb_struct x, SWIGTYPE_p_ulong y) {
    arblibJNI.arb_set_ui(arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(y));
  }

  public static void arb_set_d(arb_struct x, double y) {
    arblibJNI.arb_set_d(arb_struct.getCPtr(x), x, y);
  }

  public static void arb_set_fmpz(arb_struct x, SWIGTYPE_p_fmpz_t y) {
    arblibJNI.arb_set_fmpz(arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y));
  }

  public static void arb_set_fmpz_2exp(arb_struct x, SWIGTYPE_p_fmpz_t y, SWIGTYPE_p_fmpz_t exp) {
    arblibJNI.arb_set_fmpz_2exp(arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y), SWIGTYPE_p_fmpz_t.getCPtr(exp));
  }

  public static void arb_set_round_fmpz_2exp(arb_struct y, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_fmpz_t exp, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_set_round_fmpz_2exp(arb_struct.getCPtr(y), y, SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_fmpz_t.getCPtr(exp), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_set_round_fmpz(arb_struct y, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_set_round_fmpz(arb_struct.getCPtr(y), y, SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static int arb_is_one(arb_struct f) {
    return arblibJNI.arb_is_one(arb_struct.getCPtr(f), f);
  }

  public static void arb_one(arb_struct f) {
    arblibJNI.arb_one(arb_struct.getCPtr(f), f);
  }

  public static void arb_fprint(SWIGTYPE_p_FILE file, arb_struct x) {
    arblibJNI.arb_fprint(SWIGTYPE_p_FILE.getCPtr(file), arb_struct.getCPtr(x), x);
  }

  public static void arb_fprintd(SWIGTYPE_p_FILE file, arb_struct x, SWIGTYPE_p_slong digits) {
    arblibJNI.arb_fprintd(SWIGTYPE_p_FILE.getCPtr(file), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(digits));
  }

  public static void arb_fprintn(SWIGTYPE_p_FILE file, arb_struct x, SWIGTYPE_p_slong digits, SWIGTYPE_p_ulong flags) {
    arblibJNI.arb_fprintn(SWIGTYPE_p_FILE.getCPtr(file), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(digits), SWIGTYPE_p_ulong.getCPtr(flags));
  }

  public static void arb_print(arb_struct x) {
    arblibJNI.arb_print(arb_struct.getCPtr(x), x);
  }

  public static void arb_printd(arb_struct x, SWIGTYPE_p_slong digits) {
    arblibJNI.arb_printd(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(digits));
  }

  public static void arb_printn(arb_struct x, SWIGTYPE_p_slong digits, SWIGTYPE_p_ulong flags) {
    arblibJNI.arb_printn(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(digits), SWIGTYPE_p_ulong.getCPtr(flags));
  }

  public static void arb_mul_2exp_si(arb_struct y, arb_struct x, SWIGTYPE_p_slong e) {
    arblibJNI.arb_mul_2exp_si(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(e));
  }

  public static void arb_mul_2exp_fmpz(arb_struct y, arb_struct x, SWIGTYPE_p_fmpz_t e) {
    arblibJNI.arb_mul_2exp_fmpz(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(e));
  }

  public static int arb_is_int(arb_struct x) {
    return arblibJNI.arb_is_int(arb_struct.getCPtr(x), x);
  }

  public static int arb_is_int_2exp_si(arb_struct x, SWIGTYPE_p_slong e) {
    return arblibJNI.arb_is_int_2exp_si(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(e));
  }

  public static int arb_contains_zero(arb_struct x) {
    return arblibJNI.arb_contains_zero(arb_struct.getCPtr(x), x);
  }

  public static int arb_is_nonzero(arb_struct x) {
    return arblibJNI.arb_is_nonzero(arb_struct.getCPtr(x), x);
  }

  public static int arb_is_positive(arb_struct x) {
    return arblibJNI.arb_is_positive(arb_struct.getCPtr(x), x);
  }

  public static int arb_is_nonnegative(arb_struct x) {
    return arblibJNI.arb_is_nonnegative(arb_struct.getCPtr(x), x);
  }

  public static int arb_is_negative(arb_struct x) {
    return arblibJNI.arb_is_negative(arb_struct.getCPtr(x), x);
  }

  public static int arb_is_nonpositive(arb_struct x) {
    return arblibJNI.arb_is_nonpositive(arb_struct.getCPtr(x), x);
  }

  public static int arb_contains_negative(arb_struct x) {
    return arblibJNI.arb_contains_negative(arb_struct.getCPtr(x), x);
  }

  public static int arb_contains_nonpositive(arb_struct x) {
    return arblibJNI.arb_contains_nonpositive(arb_struct.getCPtr(x), x);
  }

  public static int arb_contains_positive(arb_struct x) {
    return arblibJNI.arb_contains_positive(arb_struct.getCPtr(x), x);
  }

  public static int arb_contains_nonnegative(arb_struct x) {
    return arblibJNI.arb_contains_nonnegative(arb_struct.getCPtr(x), x);
  }

  public static void arb_get_mag_lower(SWIGTYPE_p_mag_t z, arb_struct x) {
    arblibJNI.arb_get_mag_lower(SWIGTYPE_p_mag_t.getCPtr(z), arb_struct.getCPtr(x), x);
  }

  public static void arb_get_mag_lower_nonnegative(SWIGTYPE_p_mag_t z, arb_struct x) {
    arblibJNI.arb_get_mag_lower_nonnegative(SWIGTYPE_p_mag_t.getCPtr(z), arb_struct.getCPtr(x), x);
  }

  public static void arb_get_mag(SWIGTYPE_p_mag_t z, arb_struct x) {
    arblibJNI.arb_get_mag(SWIGTYPE_p_mag_t.getCPtr(z), arb_struct.getCPtr(x), x);
  }

  public static void arb_get_mid_arb(arb_struct z, arb_struct x) {
    arblibJNI.arb_get_mid_arb(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x);
  }

  public static void arb_get_rad_arb(arb_struct z, arb_struct x) {
    arblibJNI.arb_get_rad_arb(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x);
  }

  public static void arb_get_abs_ubound_arf(SWIGTYPE_p_arf_t u, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_get_abs_ubound_arf(SWIGTYPE_p_arf_t.getCPtr(u), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_get_abs_lbound_arf(SWIGTYPE_p_arf_t u, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_get_abs_lbound_arf(SWIGTYPE_p_arf_t.getCPtr(u), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_get_ubound_arf(SWIGTYPE_p_arf_t u, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_get_ubound_arf(SWIGTYPE_p_arf_t.getCPtr(u), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_get_lbound_arf(SWIGTYPE_p_arf_t u, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_get_lbound_arf(SWIGTYPE_p_arf_t.getCPtr(u), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_nonnegative_part(arb_struct res, arb_struct x) {
    arblibJNI.arb_nonnegative_part(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x);
  }

  public static SWIGTYPE_p_slong arb_rel_error_bits(arb_struct x) {
    return new SWIGTYPE_p_slong(arblibJNI.arb_rel_error_bits(arb_struct.getCPtr(x), x), true);
  }

  public static SWIGTYPE_p_slong arb_rel_accuracy_bits(arb_struct x) {
    return new SWIGTYPE_p_slong(arblibJNI.arb_rel_accuracy_bits(arb_struct.getCPtr(x), x), true);
  }

  public static SWIGTYPE_p_slong arb_rel_one_accuracy_bits(arb_struct x) {
    return new SWIGTYPE_p_slong(arblibJNI.arb_rel_one_accuracy_bits(arb_struct.getCPtr(x), x), true);
  }

  public static SWIGTYPE_p_slong arb_bits(arb_struct x) {
    return new SWIGTYPE_p_slong(arblibJNI.arb_bits(arb_struct.getCPtr(x), x), true);
  }

  public static void arb_randtest_exact(arb_struct x, SWIGTYPE_p_flint_rand_t state, SWIGTYPE_p_slong prec, SWIGTYPE_p_slong mag_bits) {
    arblibJNI.arb_randtest_exact(arb_struct.getCPtr(x), x, SWIGTYPE_p_flint_rand_t.getCPtr(state), SWIGTYPE_p_slong.getCPtr(prec), SWIGTYPE_p_slong.getCPtr(mag_bits));
  }

  public static void arb_randtest_wide(arb_struct x, SWIGTYPE_p_flint_rand_t state, SWIGTYPE_p_slong prec, SWIGTYPE_p_slong mag_bits) {
    arblibJNI.arb_randtest_wide(arb_struct.getCPtr(x), x, SWIGTYPE_p_flint_rand_t.getCPtr(state), SWIGTYPE_p_slong.getCPtr(prec), SWIGTYPE_p_slong.getCPtr(mag_bits));
  }

  public static void arb_randtest_precise(arb_struct x, SWIGTYPE_p_flint_rand_t state, SWIGTYPE_p_slong prec, SWIGTYPE_p_slong mag_bits) {
    arblibJNI.arb_randtest_precise(arb_struct.getCPtr(x), x, SWIGTYPE_p_flint_rand_t.getCPtr(state), SWIGTYPE_p_slong.getCPtr(prec), SWIGTYPE_p_slong.getCPtr(mag_bits));
  }

  public static void arb_randtest(arb_struct x, SWIGTYPE_p_flint_rand_t state, SWIGTYPE_p_slong prec, SWIGTYPE_p_slong mag_bits) {
    arblibJNI.arb_randtest(arb_struct.getCPtr(x), x, SWIGTYPE_p_flint_rand_t.getCPtr(state), SWIGTYPE_p_slong.getCPtr(prec), SWIGTYPE_p_slong.getCPtr(mag_bits));
  }

  public static void arb_randtest_special(arb_struct x, SWIGTYPE_p_flint_rand_t state, SWIGTYPE_p_slong prec, SWIGTYPE_p_slong mag_bits) {
    arblibJNI.arb_randtest_special(arb_struct.getCPtr(x), x, SWIGTYPE_p_flint_rand_t.getCPtr(state), SWIGTYPE_p_slong.getCPtr(prec), SWIGTYPE_p_slong.getCPtr(mag_bits));
  }

  public static void arb_add_error_arf(arb_struct x, SWIGTYPE_p_arf_t err) {
    arblibJNI.arb_add_error_arf(arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(err));
  }

  public static void arb_add_error_2exp_si(arb_struct x, SWIGTYPE_p_slong err) {
    arblibJNI.arb_add_error_2exp_si(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(err));
  }

  public static void arb_add_error_2exp_fmpz(arb_struct x, SWIGTYPE_p_fmpz_t err) {
    arblibJNI.arb_add_error_2exp_fmpz(arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(err));
  }

  public static void arb_add_error(arb_struct x, arb_struct error) {
    arblibJNI.arb_add_error(arb_struct.getCPtr(x), x, arb_struct.getCPtr(error), error);
  }

  public static void arb_add_error_mag(arb_struct x, SWIGTYPE_p_mag_t err) {
    arblibJNI.arb_add_error_mag(arb_struct.getCPtr(x), x, SWIGTYPE_p_mag_t.getCPtr(err));
  }

  public static int arb_contains_arf(arb_struct x, SWIGTYPE_p_arf_t y) {
    return arblibJNI.arb_contains_arf(arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(y));
  }

  public static int arb_contains_fmpq(arb_struct x, SWIGTYPE_p_fmpq_t y) {
    return arblibJNI.arb_contains_fmpq(arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpq_t.getCPtr(y));
  }

  public static int arb_contains_fmpz(arb_struct x, SWIGTYPE_p_fmpz_t y) {
    return arblibJNI.arb_contains_fmpz(arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y));
  }

  public static int arb_contains_si(arb_struct x, SWIGTYPE_p_slong y) {
    return arblibJNI.arb_contains_si(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y));
  }

  public static int arb_contains_mpfr(arb_struct x, SWIGTYPE_p_mpfr_t y) {
    return arblibJNI.arb_contains_mpfr(arb_struct.getCPtr(x), x, SWIGTYPE_p_mpfr_t.getCPtr(y));
  }

  public static int arb_overlaps(arb_struct x, arb_struct y) {
    return arblibJNI.arb_overlaps(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_contains(arb_struct x, arb_struct y) {
    return arblibJNI.arb_contains(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_contains_interior(arb_struct x, arb_struct y) {
    return arblibJNI.arb_contains_interior(arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y);
  }

  public static int arb_contains_int(arb_struct x) {
    return arblibJNI.arb_contains_int(arb_struct.getCPtr(x), x);
  }

  public static void arb_get_interval_fmpz_2exp(SWIGTYPE_p_fmpz_t a, SWIGTYPE_p_fmpz_t b, SWIGTYPE_p_fmpz_t exp, arb_struct x) {
    arblibJNI.arb_get_interval_fmpz_2exp(SWIGTYPE_p_fmpz_t.getCPtr(a), SWIGTYPE_p_fmpz_t.getCPtr(b), SWIGTYPE_p_fmpz_t.getCPtr(exp), arb_struct.getCPtr(x), x);
  }

  public static int arb_get_unique_fmpz(SWIGTYPE_p_fmpz_t z, arb_struct x) {
    return arblibJNI.arb_get_unique_fmpz(SWIGTYPE_p_fmpz_t.getCPtr(z), arb_struct.getCPtr(x), x);
  }

  public static void arb_get_fmpz_mid_rad_10exp(SWIGTYPE_p_fmpz_t mid, SWIGTYPE_p_fmpz_t rad, SWIGTYPE_p_fmpz_t exp, arb_struct x, SWIGTYPE_p_slong n) {
    arblibJNI.arb_get_fmpz_mid_rad_10exp(SWIGTYPE_p_fmpz_t.getCPtr(mid), SWIGTYPE_p_fmpz_t.getCPtr(rad), SWIGTYPE_p_fmpz_t.getCPtr(exp), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(n));
  }

  public static void arb_floor(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_floor(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_ceil(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_ceil(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_set_interval_arf(arb_struct x, SWIGTYPE_p_arf_t a, SWIGTYPE_p_arf_t b, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_set_interval_arf(arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(a), SWIGTYPE_p_arf_t.getCPtr(b), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_set_interval_mpfr(arb_struct x, SWIGTYPE_p_mpfr_t a, SWIGTYPE_p_mpfr_t b, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_set_interval_mpfr(arb_struct.getCPtr(x), x, SWIGTYPE_p_mpfr_t.getCPtr(a), SWIGTYPE_p_mpfr_t.getCPtr(b), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_get_interval_arf(SWIGTYPE_p_arf_t a, SWIGTYPE_p_arf_t b, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_get_interval_arf(SWIGTYPE_p_arf_t.getCPtr(a), SWIGTYPE_p_arf_t.getCPtr(b), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_get_interval_mpfr(SWIGTYPE_p_mpfr_t a, SWIGTYPE_p_mpfr_t b, arb_struct x) {
    arblibJNI.arb_get_interval_mpfr(SWIGTYPE_p_mpfr_t.getCPtr(a), SWIGTYPE_p_mpfr_t.getCPtr(b), arb_struct.getCPtr(x), x);
  }

  public static void arb_set_interval_mag(arb_struct res, SWIGTYPE_p_mag_t a, SWIGTYPE_p_mag_t b, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_set_interval_mag(arb_struct.getCPtr(res), res, SWIGTYPE_p_mag_t.getCPtr(a), SWIGTYPE_p_mag_t.getCPtr(b), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_set_interval_neg_pos_mag(arb_struct res, SWIGTYPE_p_mag_t a, SWIGTYPE_p_mag_t b, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_set_interval_neg_pos_mag(arb_struct.getCPtr(res), res, SWIGTYPE_p_mag_t.getCPtr(a), SWIGTYPE_p_mag_t.getCPtr(b), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_union(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_union(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static int arb_intersection(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    return arblibJNI.arb_intersection(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_get_rand_fmpq(SWIGTYPE_p_fmpq_t q, SWIGTYPE_p_flint_rand_t state, arb_struct x, SWIGTYPE_p_slong bits) {
    arblibJNI.arb_get_rand_fmpq(SWIGTYPE_p_fmpq_t.getCPtr(q), SWIGTYPE_p_flint_rand_t.getCPtr(state), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(bits));
  }

  public static void arb_min(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_min(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_max(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_max(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static int arb_can_round_arf(arb_struct x, SWIGTYPE_p_slong prec, SWIGTYPE_p_arf_rnd_t rnd) {
    return arblibJNI.arb_can_round_arf(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec), SWIGTYPE_p_arf_rnd_t.getCPtr(rnd));
  }

  public static int arb_can_round_mpfr(arb_struct x, SWIGTYPE_p_slong prec, SWIGTYPE_p_mpfr_rnd_t rnd) {
    return arblibJNI.arb_can_round_mpfr(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec), SWIGTYPE_p_mpfr_rnd_t.getCPtr(rnd));
  }

  public static void arb_add(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_add(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_add_arf(arb_struct z, arb_struct x, SWIGTYPE_p_arf_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_add_arf(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_add_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_add_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_add_si(arb_struct z, arb_struct x, SWIGTYPE_p_slong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_add_si(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_add_fmpz(arb_struct z, arb_struct x, SWIGTYPE_p_fmpz_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_add_fmpz(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_add_fmpz_2exp(arb_struct z, arb_struct x, SWIGTYPE_p_fmpz_t man, SWIGTYPE_p_fmpz_t exp, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_add_fmpz_2exp(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(man), SWIGTYPE_p_fmpz_t.getCPtr(exp), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sub(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sub(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sub_arf(arb_struct z, arb_struct x, SWIGTYPE_p_arf_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sub_arf(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sub_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sub_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sub_si(arb_struct z, arb_struct x, SWIGTYPE_p_slong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sub_si(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sub_fmpz(arb_struct z, arb_struct x, SWIGTYPE_p_fmpz_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sub_fmpz(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_mul(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_mul(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_mul_arf(arb_struct z, arb_struct x, SWIGTYPE_p_arf_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_mul_arf(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_mul_si(arb_struct z, arb_struct x, SWIGTYPE_p_slong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_mul_si(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_mul_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_mul_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_mul_fmpz(arb_struct z, arb_struct x, SWIGTYPE_p_fmpz_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_mul_fmpz(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_addmul(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_addmul(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_addmul_arf(arb_struct z, arb_struct x, SWIGTYPE_p_arf_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_addmul_arf(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_addmul_si(arb_struct z, arb_struct x, SWIGTYPE_p_slong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_addmul_si(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_addmul_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_addmul_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_addmul_fmpz(arb_struct z, arb_struct x, SWIGTYPE_p_fmpz_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_addmul_fmpz(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_submul(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_submul(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_submul_arf(arb_struct z, arb_struct x, SWIGTYPE_p_arf_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_submul_arf(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_submul_si(arb_struct z, arb_struct x, SWIGTYPE_p_slong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_submul_si(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_submul_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_submul_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_submul_fmpz(arb_struct z, arb_struct x, SWIGTYPE_p_fmpz_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_submul_fmpz(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_dot_simple(arb_struct res, arb_struct initial, int subtract, arb_struct x, SWIGTYPE_p_slong xstep, arb_struct y, SWIGTYPE_p_slong ystep, SWIGTYPE_p_slong len, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_dot_simple(arb_struct.getCPtr(res), res, arb_struct.getCPtr(initial), initial, subtract, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(xstep), arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(ystep), SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_dot_precise(arb_struct res, arb_struct initial, int subtract, arb_struct x, SWIGTYPE_p_slong xstep, arb_struct y, SWIGTYPE_p_slong ystep, SWIGTYPE_p_slong len, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_dot_precise(arb_struct.getCPtr(res), res, arb_struct.getCPtr(initial), initial, subtract, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(xstep), arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(ystep), SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_dot(arb_struct res, arb_struct initial, int subtract, arb_struct x, SWIGTYPE_p_slong xstep, arb_struct y, SWIGTYPE_p_slong ystep, SWIGTYPE_p_slong len, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_dot(arb_struct.getCPtr(res), res, arb_struct.getCPtr(initial), initial, subtract, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(xstep), arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(ystep), SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_approx_dot(arb_struct res, arb_struct initial, int subtract, arb_struct x, SWIGTYPE_p_slong xstep, arb_struct y, SWIGTYPE_p_slong ystep, SWIGTYPE_p_slong len, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_approx_dot(arb_struct.getCPtr(res), res, arb_struct.getCPtr(initial), initial, subtract, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(xstep), arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(ystep), SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_div(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_div(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_div_arf(arb_struct z, arb_struct x, SWIGTYPE_p_arf_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_div_arf(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_arf_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_div_si(arb_struct z, arb_struct x, SWIGTYPE_p_slong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_div_si(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_div_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_div_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_div_fmpz(arb_struct z, arb_struct x, SWIGTYPE_p_fmpz_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_div_fmpz(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpz_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_fmpz_div_fmpz(arb_struct z, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_fmpz_t y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_fmpz_div_fmpz(arb_struct.getCPtr(z), z, SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_fmpz_t.getCPtr(y), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_ui_div(arb_struct z, SWIGTYPE_p_ulong x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_ui_div(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(x), arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_inv(arb_struct y, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_inv(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_set_fmpq(arb_struct y, SWIGTYPE_p_fmpq_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_set_fmpq(arb_struct.getCPtr(y), y, SWIGTYPE_p_fmpq_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sqrt(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sqrt(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sqrt_arf(arb_struct z, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sqrt_arf(arb_struct.getCPtr(z), z, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sqrt_fmpz(arb_struct z, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sqrt_fmpz(arb_struct.getCPtr(z), z, SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sqrt_ui(arb_struct z, SWIGTYPE_p_ulong x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sqrt_ui(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sqrtpos(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sqrtpos(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_hypot(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_hypot(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rsqrt(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rsqrt(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rsqrt_ui(arb_struct z, SWIGTYPE_p_ulong x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rsqrt_ui(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sqrt1pm1(arb_struct r, arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sqrt1pm1(arb_struct.getCPtr(r), r, arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_pow_fmpz_binexp(arb_struct y, arb_struct b, SWIGTYPE_p_fmpz_t e, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_pow_fmpz_binexp(arb_struct.getCPtr(y), y, arb_struct.getCPtr(b), b, SWIGTYPE_p_fmpz_t.getCPtr(e), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_pow_fmpz(arb_struct y, arb_struct b, SWIGTYPE_p_fmpz_t e, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_pow_fmpz(arb_struct.getCPtr(y), y, arb_struct.getCPtr(b), b, SWIGTYPE_p_fmpz_t.getCPtr(e), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_pow_ui(arb_struct y, arb_struct b, SWIGTYPE_p_ulong e, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_pow_ui(arb_struct.getCPtr(y), y, arb_struct.getCPtr(b), b, SWIGTYPE_p_ulong.getCPtr(e), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_ui_pow_ui(arb_struct y, SWIGTYPE_p_ulong b, SWIGTYPE_p_ulong e, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_ui_pow_ui(arb_struct.getCPtr(y), y, SWIGTYPE_p_ulong.getCPtr(b), SWIGTYPE_p_ulong.getCPtr(e), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_si_pow_ui(arb_struct y, SWIGTYPE_p_slong b, SWIGTYPE_p_ulong e, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_si_pow_ui(arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(b), SWIGTYPE_p_ulong.getCPtr(e), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_pow_fmpq(arb_struct y, arb_struct x, SWIGTYPE_p_fmpq_t a, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_pow_fmpq(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_fmpq_t.getCPtr(a), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_div_2expm1_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_div_2expm1_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_pow(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_pow(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_root_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong k, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_root_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(k), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_root(arb_struct z, arb_struct x, SWIGTYPE_p_ulong k, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_root(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(k), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_log(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_log(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_log_arf(arb_struct z, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_log_arf(arb_struct.getCPtr(z), z, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_log_ui(arb_struct z, SWIGTYPE_p_ulong x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_log_ui(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_log_fmpz(arb_struct z, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_log_fmpz(arb_struct.getCPtr(z), z, SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_log1p(arb_struct r, arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_log1p(arb_struct.getCPtr(r), r, arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_log_base_ui(arb_struct res, arb_struct x, SWIGTYPE_p_ulong b, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_log_base_ui(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(b), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_log_hypot(arb_struct res, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_log_hypot(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_exp(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_exp(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_expm1(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_expm1(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_exp_invexp(arb_struct z, arb_struct w, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_exp_invexp(arb_struct.getCPtr(z), z, arb_struct.getCPtr(w), w, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin(arb_struct s, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin(arb_struct.getCPtr(s), s, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_cos(arb_struct c, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_cos(arb_struct.getCPtr(c), c, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_cos(arb_struct s, arb_struct c, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_cos(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_pi(arb_struct s, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_pi(arb_struct.getCPtr(s), s, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_cos_pi(arb_struct c, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_cos_pi(arb_struct.getCPtr(c), c, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_cos_pi(arb_struct s, arb_struct c, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_cos_pi(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_tan(arb_struct y, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_tan(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_cot(arb_struct y, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_cot(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_tan_pi(arb_struct y, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_tan_pi(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_cot_pi(arb_struct y, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_cot_pi(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_sin_pi_fmpq_algebraic(arb_struct s, SWIGTYPE_p_ulong p, SWIGTYPE_p_ulong q, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_sin_pi_fmpq_algebraic(arb_struct.getCPtr(s), s, SWIGTYPE_p_ulong.getCPtr(p), SWIGTYPE_p_ulong.getCPtr(q), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_cos_pi_fmpq_algebraic(arb_struct c, SWIGTYPE_p_ulong p, SWIGTYPE_p_ulong q, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_cos_pi_fmpq_algebraic(arb_struct.getCPtr(c), c, SWIGTYPE_p_ulong.getCPtr(p), SWIGTYPE_p_ulong.getCPtr(q), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_sin_cos_pi_fmpq_algebraic(arb_struct s, arb_struct c, SWIGTYPE_p_ulong p, SWIGTYPE_p_ulong q, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_sin_cos_pi_fmpq_algebraic(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, SWIGTYPE_p_ulong.getCPtr(p), SWIGTYPE_p_ulong.getCPtr(q), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_cos_pi_fmpq(arb_struct s, arb_struct c, SWIGTYPE_p_fmpq_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_cos_pi_fmpq(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, SWIGTYPE_p_fmpq_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_pi_fmpq(arb_struct s, SWIGTYPE_p_fmpq_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_pi_fmpq(arb_struct.getCPtr(s), s, SWIGTYPE_p_fmpq_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_cos_pi_fmpq(arb_struct c, SWIGTYPE_p_fmpq_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_cos_pi_fmpq(arb_struct.getCPtr(c), c, SWIGTYPE_p_fmpq_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sinc(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sinc(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sinc_pi(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sinc_pi(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sinh(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sinh(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_cosh(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_cosh(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sinh_cosh(arb_struct s, arb_struct c, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sinh_cosh(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_tanh(arb_struct y, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_tanh(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_coth(arb_struct y, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_coth(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_atan_arf(arb_struct z, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_atan_arf(arb_struct.getCPtr(z), z, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_atan(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_atan(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_atan2(arb_struct z, arb_struct b, arb_struct a, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_atan2(arb_struct.getCPtr(z), z, arb_struct.getCPtr(b), b, arb_struct.getCPtr(a), a, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_asin(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_asin(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_acos(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_acos(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_atanh(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_atanh(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_asinh(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_asinh(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_acosh(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_acosh(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sec(arb_struct res, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sec(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_csc(arb_struct res, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_csc(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sech(arb_struct res, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sech(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_csch(arb_struct res, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_csch(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_fac_ui(arb_struct z, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_fac_ui(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_doublefac_ui(arb_struct z, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_doublefac_ui(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bin_ui(arb_struct z, arb_struct n, SWIGTYPE_p_ulong k, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bin_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(n), n, SWIGTYPE_p_ulong.getCPtr(k), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bin_uiui(arb_struct z, SWIGTYPE_p_ulong n, SWIGTYPE_p_ulong k, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bin_uiui(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_ulong.getCPtr(k), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_fib_fmpz(arb_struct z, SWIGTYPE_p_fmpz_t n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_fib_fmpz(arb_struct.getCPtr(z), z, SWIGTYPE_p_fmpz_t.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_fib_ui(arb_struct z, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_fib_ui(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_pi(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_pi(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_sqrt_pi(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_sqrt_pi(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_log_sqrt2pi(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_log_sqrt2pi(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_log2(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_log2(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_log10(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_log10(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_euler(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_euler(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_catalan(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_catalan(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_e(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_e(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_khinchin(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_khinchin(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_glaisher(arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_glaisher(arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_agm(arb_struct z, arb_struct x, arb_struct y, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_agm(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(y), y, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_lgamma(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_lgamma(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rgamma(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rgamma(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_gamma(arb_struct z, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_gamma(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_gamma_fmpq(arb_struct z, SWIGTYPE_p_fmpq_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_gamma_fmpq(arb_struct.getCPtr(z), z, SWIGTYPE_p_fmpq_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_gamma_fmpz(arb_struct z, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_gamma_fmpz(arb_struct.getCPtr(z), z, SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_digamma(arb_struct y, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_digamma(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta(arb_struct z, arb_struct s, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta(arb_struct.getCPtr(z), z, arb_struct.getCPtr(s), s, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_hurwitz_zeta(arb_struct z, arb_struct s, arb_struct a, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_hurwitz_zeta(arb_struct.getCPtr(z), z, arb_struct.getCPtr(s), s, arb_struct.getCPtr(a), a, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising_ui_bs(arb_struct y, arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising_ui_bs(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising_ui_rs(arb_struct y, arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_ulong m, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising_ui_rs(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_ulong.getCPtr(m), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising_ui_rec(arb_struct y, arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising_ui_rec(arb_struct.getCPtr(y), y, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising_ui(arb_struct z, arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising_ui(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising_fmpq_ui(arb_struct y, SWIGTYPE_p_fmpq_t x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising_fmpq_ui(arb_struct.getCPtr(y), y, SWIGTYPE_p_fmpq_t.getCPtr(x), SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising(arb_struct z, arb_struct x, arb_struct n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising(arb_struct.getCPtr(z), z, arb_struct.getCPtr(x), x, arb_struct.getCPtr(n), n, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising2_ui_rs(arb_struct u, arb_struct v, arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_ulong m, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising2_ui_rs(arb_struct.getCPtr(u), u, arb_struct.getCPtr(v), v, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_ulong.getCPtr(m), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising2_ui_bs(arb_struct u, arb_struct v, arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising2_ui_bs(arb_struct.getCPtr(u), u, arb_struct.getCPtr(v), v, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_rising2_ui(arb_struct u, arb_struct v, arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_rising2_ui(arb_struct.getCPtr(u), u, arb_struct.getCPtr(v), v, arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_log_ui_from_prev(arb_struct s, SWIGTYPE_p_ulong k, arb_struct log_prev, SWIGTYPE_p_ulong prev, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_log_ui_from_prev(arb_struct.getCPtr(s), s, SWIGTYPE_p_ulong.getCPtr(k), arb_struct.getCPtr(log_prev), log_prev, SWIGTYPE_p_ulong.getCPtr(prev), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_const_apery(arb_struct s, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_const_apery(arb_struct.getCPtr(s), s, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui_asymp(arb_struct x, SWIGTYPE_p_ulong s, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui_asymp(arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(s), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui_borwein_bsplit(arb_struct x, SWIGTYPE_p_ulong s, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui_borwein_bsplit(arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(s), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui_euler_product(arb_struct z, SWIGTYPE_p_ulong s, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui_euler_product(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(s), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui_bernoulli(arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui_bernoulli(arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui_vec_borwein(arb_struct z, SWIGTYPE_p_ulong start, SWIGTYPE_p_slong num, SWIGTYPE_p_ulong step, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui_vec_borwein(arb_struct.getCPtr(z), z, SWIGTYPE_p_ulong.getCPtr(start), SWIGTYPE_p_slong.getCPtr(num), SWIGTYPE_p_ulong.getCPtr(step), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui(arb_struct x, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui(arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui_vec_even(arb_struct x, SWIGTYPE_p_ulong start, SWIGTYPE_p_slong num, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui_vec_even(arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(start), SWIGTYPE_p_slong.getCPtr(num), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui_vec_odd(arb_struct x, SWIGTYPE_p_ulong start, SWIGTYPE_p_slong num, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui_vec_odd(arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(start), SWIGTYPE_p_slong.getCPtr(num), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_zeta_ui_vec(arb_struct x, SWIGTYPE_p_ulong start, SWIGTYPE_p_slong num, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_zeta_ui_vec(arb_struct.getCPtr(x), x, SWIGTYPE_p_ulong.getCPtr(start), SWIGTYPE_p_slong.getCPtr(num), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bernoulli_ui(arb_struct b, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bernoulli_ui(arb_struct.getCPtr(b), b, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bernoulli_ui_zeta(arb_struct b, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bernoulli_ui_zeta(arb_struct.getCPtr(b), b, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bernoulli_fmpz(arb_struct b, SWIGTYPE_p_fmpz_t n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bernoulli_fmpz(arb_struct.getCPtr(b), b, SWIGTYPE_p_fmpz_t.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bernoulli_poly_ui(arb_struct res, SWIGTYPE_p_ulong n, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bernoulli_poly_ui(arb_struct.getCPtr(res), res, SWIGTYPE_p_ulong.getCPtr(n), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_polylog(arb_struct w, arb_struct s, arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_polylog(arb_struct.getCPtr(w), w, arb_struct.getCPtr(s), s, arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_polylog_si(arb_struct w, SWIGTYPE_p_slong s, arb_struct z, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_polylog_si(arb_struct.getCPtr(w), w, SWIGTYPE_p_slong.getCPtr(s), arb_struct.getCPtr(z), z, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_chebyshev_t_ui(arb_struct a, SWIGTYPE_p_ulong n, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_chebyshev_t_ui(arb_struct.getCPtr(a), a, SWIGTYPE_p_ulong.getCPtr(n), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_chebyshev_t2_ui(arb_struct a, arb_struct b, SWIGTYPE_p_ulong n, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_chebyshev_t2_ui(arb_struct.getCPtr(a), a, arb_struct.getCPtr(b), b, SWIGTYPE_p_ulong.getCPtr(n), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_chebyshev_u_ui(arb_struct a, SWIGTYPE_p_ulong n, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_chebyshev_u_ui(arb_struct.getCPtr(a), a, SWIGTYPE_p_ulong.getCPtr(n), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_chebyshev_u2_ui(arb_struct a, arb_struct b, SWIGTYPE_p_ulong n, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_chebyshev_u2_ui(arb_struct.getCPtr(a), a, arb_struct.getCPtr(b), b, SWIGTYPE_p_ulong.getCPtr(n), arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_power_sum_vec(arb_struct res, arb_struct a, arb_struct b, SWIGTYPE_p_slong len, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_power_sum_vec(arb_struct.getCPtr(res), res, arb_struct.getCPtr(a), a, arb_struct.getCPtr(b), b, SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bell_sum_taylor(arb_struct res, SWIGTYPE_p_fmpz_t n, SWIGTYPE_p_fmpz_t a, SWIGTYPE_p_fmpz_t b, SWIGTYPE_p_fmpz_t mmag, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bell_sum_taylor(arb_struct.getCPtr(res), res, SWIGTYPE_p_fmpz_t.getCPtr(n), SWIGTYPE_p_fmpz_t.getCPtr(a), SWIGTYPE_p_fmpz_t.getCPtr(b), SWIGTYPE_p_fmpz_t.getCPtr(mmag), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bell_sum_bsplit(arb_struct res, SWIGTYPE_p_fmpz_t n, SWIGTYPE_p_fmpz_t a, SWIGTYPE_p_fmpz_t b, SWIGTYPE_p_fmpz_t mmag, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bell_sum_bsplit(arb_struct.getCPtr(res), res, SWIGTYPE_p_fmpz_t.getCPtr(n), SWIGTYPE_p_fmpz_t.getCPtr(a), SWIGTYPE_p_fmpz_t.getCPtr(b), SWIGTYPE_p_fmpz_t.getCPtr(mmag), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bell_fmpz(arb_struct res, SWIGTYPE_p_fmpz_t n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bell_fmpz(arb_struct.getCPtr(res), res, SWIGTYPE_p_fmpz_t.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_bell_ui(arb_struct res, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_bell_ui(arb_struct.getCPtr(res), res, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_euler_number_fmpz(arb_struct res, SWIGTYPE_p_fmpz_t n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_euler_number_fmpz(arb_struct.getCPtr(res), res, SWIGTYPE_p_fmpz_t.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_euler_number_ui(arb_struct res, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_euler_number_ui(arb_struct.getCPtr(res), res, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_partitions_fmpz(arb_struct res, SWIGTYPE_p_fmpz_t n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_partitions_fmpz(arb_struct.getCPtr(res), res, SWIGTYPE_p_fmpz_t.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_partitions_ui(arb_struct res, SWIGTYPE_p_ulong n, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_partitions_ui(arb_struct.getCPtr(res), res, SWIGTYPE_p_ulong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_lambertw(arb_struct res, arb_struct x, int flags, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_lambertw(arb_struct.getCPtr(res), res, arb_struct.getCPtr(x), x, flags, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sqr(arb_struct res, arb_struct val, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sqr(arb_struct.getCPtr(res), res, arb_struct.getCPtr(val), val, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static arb_struct _arb_vec_entry_ptr(arb_struct vec, SWIGTYPE_p_slong i) {
    long cPtr = arblibJNI._arb_vec_entry_ptr(arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(i));
    return (cPtr == 0) ? null : new arb_struct(cPtr, false);
  }

  public static void _arb_vec_zero(arb_struct A, SWIGTYPE_p_slong n) {
    arblibJNI._arb_vec_zero(arb_struct.getCPtr(A), A, SWIGTYPE_p_slong.getCPtr(n));
  }

  public static int _arb_vec_is_zero(arb_struct vec, SWIGTYPE_p_slong len) {
    return arblibJNI._arb_vec_is_zero(arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len));
  }

  public static int _arb_vec_is_finite(arb_struct x, SWIGTYPE_p_slong len) {
    return arblibJNI._arb_vec_is_finite(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(len));
  }

  public static void _arb_vec_set(arb_struct res, arb_struct vec, SWIGTYPE_p_slong len) {
    arblibJNI._arb_vec_set(arb_struct.getCPtr(res), res, arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len));
  }

  public static void _arb_vec_set_round(arb_struct res, arb_struct vec, SWIGTYPE_p_slong len, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_vec_set_round(arb_struct.getCPtr(res), res, arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_vec_swap(arb_struct res, arb_struct vec, SWIGTYPE_p_slong len) {
    arblibJNI._arb_vec_swap(arb_struct.getCPtr(res), res, arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len));
  }

  public static void _arb_vec_neg(arb_struct B, arb_struct A, SWIGTYPE_p_slong n) {
    arblibJNI._arb_vec_neg(arb_struct.getCPtr(B), B, arb_struct.getCPtr(A), A, SWIGTYPE_p_slong.getCPtr(n));
  }

  public static void _arb_vec_sub(arb_struct C, arb_struct A, arb_struct B, SWIGTYPE_p_slong n, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_vec_sub(arb_struct.getCPtr(C), C, arb_struct.getCPtr(A), A, arb_struct.getCPtr(B), B, SWIGTYPE_p_slong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_vec_add(arb_struct C, arb_struct A, arb_struct B, SWIGTYPE_p_slong n, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_vec_add(arb_struct.getCPtr(C), C, arb_struct.getCPtr(A), A, arb_struct.getCPtr(B), B, SWIGTYPE_p_slong.getCPtr(n), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_vec_scalar_mul(arb_struct res, arb_struct vec, SWIGTYPE_p_slong len, arb_struct c, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_vec_scalar_mul(arb_struct.getCPtr(res), res, arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len), arb_struct.getCPtr(c), c, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_vec_scalar_div(arb_struct res, arb_struct vec, SWIGTYPE_p_slong len, arb_struct c, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_vec_scalar_div(arb_struct.getCPtr(res), res, arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len), arb_struct.getCPtr(c), c, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_vec_scalar_mul_fmpz(arb_struct res, arb_struct vec, SWIGTYPE_p_slong len, SWIGTYPE_p_fmpz_t c, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_vec_scalar_mul_fmpz(arb_struct.getCPtr(res), res, arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_fmpz_t.getCPtr(c), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_vec_scalar_mul_2exp_si(arb_struct res, arb_struct src, SWIGTYPE_p_slong len, SWIGTYPE_p_slong c) {
    arblibJNI._arb_vec_scalar_mul_2exp_si(arb_struct.getCPtr(res), res, arb_struct.getCPtr(src), src, SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(c));
  }

  public static void _arb_vec_scalar_addmul(arb_struct res, arb_struct vec, SWIGTYPE_p_slong len, arb_struct c, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_vec_scalar_addmul(arb_struct.getCPtr(res), res, arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len), arb_struct.getCPtr(c), c, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_vec_get_mag(SWIGTYPE_p_mag_t bound, arb_struct vec, SWIGTYPE_p_slong len) {
    arblibJNI._arb_vec_get_mag(SWIGTYPE_p_mag_t.getCPtr(bound), arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len));
  }

  public static SWIGTYPE_p_slong _arb_vec_bits(arb_struct x, SWIGTYPE_p_slong len) {
    return new SWIGTYPE_p_slong(arblibJNI._arb_vec_bits(arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(len)), true);
  }

  public static void _arb_vec_set_powers(arb_struct xs, arb_struct x, SWIGTYPE_p_slong len, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_vec_set_powers(arb_struct.getCPtr(xs), xs, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_vec_add_error_arf_vec(arb_struct res, SWIGTYPE_p_arf_srcptr err, SWIGTYPE_p_slong len) {
    arblibJNI._arb_vec_add_error_arf_vec(arb_struct.getCPtr(res), res, SWIGTYPE_p_arf_srcptr.getCPtr(err), SWIGTYPE_p_slong.getCPtr(len));
  }

  public static void _arb_vec_add_error_mag_vec(arb_struct res, SWIGTYPE_p_mag_srcptr err, SWIGTYPE_p_slong len) {
    arblibJNI._arb_vec_add_error_mag_vec(arb_struct.getCPtr(res), res, SWIGTYPE_p_mag_srcptr.getCPtr(err), SWIGTYPE_p_slong.getCPtr(len));
  }

  public static void _arb_vec_indeterminate(arb_struct vec, SWIGTYPE_p_slong len) {
    arblibJNI._arb_vec_indeterminate(arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len));
  }

  public static void _arb_vec_trim(arb_struct res, arb_struct vec, SWIGTYPE_p_slong len) {
    arblibJNI._arb_vec_trim(arb_struct.getCPtr(res), res, arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len));
  }

  public static int _arb_vec_get_unique_fmpz_vec(SWIGTYPE_p_fmpz res, arb_struct vec, SWIGTYPE_p_slong len) {
    return arblibJNI._arb_vec_get_unique_fmpz_vec(SWIGTYPE_p_fmpz.getCPtr(res), arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len));
  }

  public static SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t getArb_atan_tab1() {
    long cPtr = arblibJNI.arb_atan_tab1_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t getArb_atan_tab21() {
    long cPtr = arblibJNI.arb_atan_tab21_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t getArb_atan_tab22() {
    long cPtr = arblibJNI.arb_atan_tab22_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_mp_limb_t getArb_atan_pi2_minus_one() {
    long cPtr = arblibJNI.arb_atan_pi2_minus_one_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_mp_limb_t(cPtr, false);
  }

  public static void _arb_atan_taylor_naive(SWIGTYPE_p_mp_ptr y, SWIGTYPE_p_mp_limb_t error, SWIGTYPE_p_mp_srcptr x, SWIGTYPE_p_mp_size_t xn, SWIGTYPE_p_ulong N, int alternating) {
    arblibJNI._arb_atan_taylor_naive(SWIGTYPE_p_mp_ptr.getCPtr(y), SWIGTYPE_p_mp_limb_t.getCPtr(error), SWIGTYPE_p_mp_srcptr.getCPtr(x), SWIGTYPE_p_mp_size_t.getCPtr(xn), SWIGTYPE_p_ulong.getCPtr(N), alternating);
  }

  public static void _arb_atan_taylor_rs(SWIGTYPE_p_mp_ptr y, SWIGTYPE_p_mp_limb_t error, SWIGTYPE_p_mp_srcptr x, SWIGTYPE_p_mp_size_t xn, SWIGTYPE_p_ulong N, int alternating) {
    arblibJNI._arb_atan_taylor_rs(SWIGTYPE_p_mp_ptr.getCPtr(y), SWIGTYPE_p_mp_limb_t.getCPtr(error), SWIGTYPE_p_mp_srcptr.getCPtr(x), SWIGTYPE_p_mp_size_t.getCPtr(xn), SWIGTYPE_p_ulong.getCPtr(N), alternating);
  }

  public static SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t getArb_log_tab11() {
    long cPtr = arblibJNI.arb_log_tab11_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t getArb_log_tab12() {
    long cPtr = arblibJNI.arb_log_tab12_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t getArb_log_tab21() {
    long cPtr = arblibJNI.arb_log_tab21_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t getArb_log_tab22() {
    long cPtr = arblibJNI.arb_log_tab22_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_mp_limb_t getArb_log_log2_tab() {
    long cPtr = arblibJNI.arb_log_log2_tab_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t getArb_exp_tab1() {
    long cPtr = arblibJNI.arb_exp_tab1_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t getArb_exp_tab21() {
    long cPtr = arblibJNI.arb_exp_tab21_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t getArb_exp_tab22() {
    long cPtr = arblibJNI.arb_exp_tab22_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static void _arb_exp_taylor_naive(SWIGTYPE_p_mp_ptr y, SWIGTYPE_p_mp_limb_t error, SWIGTYPE_p_mp_srcptr x, SWIGTYPE_p_mp_size_t xn, SWIGTYPE_p_ulong N) {
    arblibJNI._arb_exp_taylor_naive(SWIGTYPE_p_mp_ptr.getCPtr(y), SWIGTYPE_p_mp_limb_t.getCPtr(error), SWIGTYPE_p_mp_srcptr.getCPtr(x), SWIGTYPE_p_mp_size_t.getCPtr(xn), SWIGTYPE_p_ulong.getCPtr(N));
  }

  public static void _arb_exp_taylor_rs(SWIGTYPE_p_mp_ptr y, SWIGTYPE_p_mp_limb_t error, SWIGTYPE_p_mp_srcptr x, SWIGTYPE_p_mp_size_t xn, SWIGTYPE_p_ulong N) {
    arblibJNI._arb_exp_taylor_rs(SWIGTYPE_p_mp_ptr.getCPtr(y), SWIGTYPE_p_mp_limb_t.getCPtr(error), SWIGTYPE_p_mp_srcptr.getCPtr(x), SWIGTYPE_p_mp_size_t.getCPtr(xn), SWIGTYPE_p_ulong.getCPtr(N));
  }

  public static void arb_exp_arf_bb(arb_struct z, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec, int minus_one) {
    arblibJNI.arb_exp_arf_bb(arb_struct.getCPtr(z), z, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec), minus_one);
  }

  public static void arb_exp_arf_rs_generic(arb_struct res, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec, int minus_one) {
    arblibJNI.arb_exp_arf_rs_generic(arb_struct.getCPtr(res), res, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec), minus_one);
  }

  public static int _arb_get_mpn_fixed_mod_log2(SWIGTYPE_p_mp_ptr w, SWIGTYPE_p_fmpz_t q, SWIGTYPE_p_mp_limb_t error, SWIGTYPE_p_arf_t x, SWIGTYPE_p_mp_size_t wn) {
    return arblibJNI._arb_get_mpn_fixed_mod_log2(SWIGTYPE_p_mp_ptr.getCPtr(w), SWIGTYPE_p_fmpz_t.getCPtr(q), SWIGTYPE_p_mp_limb_t.getCPtr(error), SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_mp_size_t.getCPtr(wn));
  }

  public static SWIGTYPE_p_slong _arb_exp_taylor_bound(SWIGTYPE_p_slong mag, SWIGTYPE_p_slong prec) {
    return new SWIGTYPE_p_slong(arblibJNI._arb_exp_taylor_bound(SWIGTYPE_p_slong.getCPtr(mag), SWIGTYPE_p_slong.getCPtr(prec)), true);
  }

  public static void _arb_exp_sum_bs_powtab(SWIGTYPE_p_fmpz_t T, SWIGTYPE_p_fmpz_t Q, SWIGTYPE_p_flint_bitcnt_t Qexp, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_flint_bitcnt_t r, SWIGTYPE_p_slong N) {
    arblibJNI._arb_exp_sum_bs_powtab(SWIGTYPE_p_fmpz_t.getCPtr(T), SWIGTYPE_p_fmpz_t.getCPtr(Q), SWIGTYPE_p_flint_bitcnt_t.getCPtr(Qexp), SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_flint_bitcnt_t.getCPtr(r), SWIGTYPE_p_slong.getCPtr(N));
  }

  public static void _arb_exp_sum_bs_simple(SWIGTYPE_p_fmpz_t T, SWIGTYPE_p_fmpz_t Q, SWIGTYPE_p_flint_bitcnt_t Qexp, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_flint_bitcnt_t r, SWIGTYPE_p_slong N) {
    arblibJNI._arb_exp_sum_bs_simple(SWIGTYPE_p_fmpz_t.getCPtr(T), SWIGTYPE_p_fmpz_t.getCPtr(Q), SWIGTYPE_p_flint_bitcnt_t.getCPtr(Qexp), SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_flint_bitcnt_t.getCPtr(r), SWIGTYPE_p_slong.getCPtr(N));
  }

  public static SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t getArb_sin_cos_tab1() {
    long cPtr = arblibJNI.arb_sin_cos_tab1_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__512_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t getArb_sin_cos_tab21() {
    long cPtr = arblibJNI.arb_sin_cos_tab21_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t getArb_sin_cos_tab22() {
    long cPtr = arblibJNI.arb_sin_cos_tab22_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a__4608_FLINT_BITS___mp_limb_t(cPtr, false);
  }

  public static SWIGTYPE_p_mp_limb_t getArb_pi4_tab() {
    long cPtr = arblibJNI.arb_pi4_tab_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_mp_limb_t(cPtr, false);
  }

  public static void _arb_sin_cos_taylor_naive(SWIGTYPE_p_mp_ptr ysin, SWIGTYPE_p_mp_ptr ycos, SWIGTYPE_p_mp_limb_t error, SWIGTYPE_p_mp_srcptr x, SWIGTYPE_p_mp_size_t xn, SWIGTYPE_p_ulong N) {
    arblibJNI._arb_sin_cos_taylor_naive(SWIGTYPE_p_mp_ptr.getCPtr(ysin), SWIGTYPE_p_mp_ptr.getCPtr(ycos), SWIGTYPE_p_mp_limb_t.getCPtr(error), SWIGTYPE_p_mp_srcptr.getCPtr(x), SWIGTYPE_p_mp_size_t.getCPtr(xn), SWIGTYPE_p_ulong.getCPtr(N));
  }

  public static void _arb_sin_cos_taylor_rs(SWIGTYPE_p_mp_ptr ysin, SWIGTYPE_p_mp_ptr ycos, SWIGTYPE_p_mp_limb_t error, SWIGTYPE_p_mp_srcptr x, SWIGTYPE_p_mp_size_t xn, SWIGTYPE_p_ulong N, int sinonly, int alternating) {
    arblibJNI._arb_sin_cos_taylor_rs(SWIGTYPE_p_mp_ptr.getCPtr(ysin), SWIGTYPE_p_mp_ptr.getCPtr(ycos), SWIGTYPE_p_mp_limb_t.getCPtr(error), SWIGTYPE_p_mp_srcptr.getCPtr(x), SWIGTYPE_p_mp_size_t.getCPtr(xn), SWIGTYPE_p_ulong.getCPtr(N), sinonly, alternating);
  }

  public static int _arb_get_mpn_fixed_mod_pi4(SWIGTYPE_p_mp_ptr w, SWIGTYPE_p_fmpz_t q, SWIGTYPE_p_int octant, SWIGTYPE_p_mp_limb_t error, SWIGTYPE_p_arf_t x, SWIGTYPE_p_mp_size_t wn) {
    return arblibJNI._arb_get_mpn_fixed_mod_pi4(SWIGTYPE_p_mp_ptr.getCPtr(w), SWIGTYPE_p_fmpz_t.getCPtr(q), SWIGTYPE_p_int.getCPtr(octant), SWIGTYPE_p_mp_limb_t.getCPtr(error), SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_mp_size_t.getCPtr(wn));
  }

  public static void arb_sin_cos_arf_bb(arb_struct zsin, arb_struct zcos, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_cos_arf_bb(arb_struct.getCPtr(zsin), zsin, arb_struct.getCPtr(zcos), zcos, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_cos_arf_rs_generic(arb_struct res_sin, arb_struct res_cos, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_cos_arf_rs_generic(arb_struct.getCPtr(res_sin), res_sin, arb_struct.getCPtr(res_cos), res_cos, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_cos_arf_generic(arb_struct res_sin, arb_struct res_cos, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_cos_arf_generic(arb_struct.getCPtr(res_sin), res_sin, arb_struct.getCPtr(res_cos), res_cos, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_sin_cos_wide(arb_struct s, arb_struct c, SWIGTYPE_p_arf_t x, SWIGTYPE_p_mag_t r, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_sin_cos_wide(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_mag_t.getCPtr(r), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_cos_wide(arb_struct s, arb_struct c, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_cos_wide(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void _arb_sin_cos_generic(arb_struct s, arb_struct c, SWIGTYPE_p_arf_t x, SWIGTYPE_p_mag_t xrad, SWIGTYPE_p_slong prec) {
    arblibJNI._arb_sin_cos_generic(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_mag_t.getCPtr(xrad), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static void arb_sin_cos_generic(arb_struct s, arb_struct c, arb_struct x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_sin_cos_generic(arb_struct.getCPtr(s), s, arb_struct.getCPtr(c), c, arb_struct.getCPtr(x), x, SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static SWIGTYPE_p_flint_bitcnt_t _arb_mpn_leading_zeros(SWIGTYPE_p_mp_srcptr d, SWIGTYPE_p_mp_size_t n) {
    return new SWIGTYPE_p_flint_bitcnt_t(arblibJNI._arb_mpn_leading_zeros(SWIGTYPE_p_mp_srcptr.getCPtr(d), SWIGTYPE_p_mp_size_t.getCPtr(n)), true);
  }

  public static void _arb_atan_sum_bs_simple(SWIGTYPE_p_fmpz_t T, SWIGTYPE_p_fmpz_t Q, SWIGTYPE_p_flint_bitcnt_t Qexp, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_flint_bitcnt_t r, SWIGTYPE_p_slong N) {
    arblibJNI._arb_atan_sum_bs_simple(SWIGTYPE_p_fmpz_t.getCPtr(T), SWIGTYPE_p_fmpz_t.getCPtr(Q), SWIGTYPE_p_flint_bitcnt_t.getCPtr(Qexp), SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_flint_bitcnt_t.getCPtr(r), SWIGTYPE_p_slong.getCPtr(N));
  }

  public static void _arb_atan_sum_bs_powtab(SWIGTYPE_p_fmpz_t T, SWIGTYPE_p_fmpz_t Q, SWIGTYPE_p_flint_bitcnt_t Qexp, SWIGTYPE_p_fmpz_t x, SWIGTYPE_p_flint_bitcnt_t r, SWIGTYPE_p_slong N) {
    arblibJNI._arb_atan_sum_bs_powtab(SWIGTYPE_p_fmpz_t.getCPtr(T), SWIGTYPE_p_fmpz_t.getCPtr(Q), SWIGTYPE_p_flint_bitcnt_t.getCPtr(Qexp), SWIGTYPE_p_fmpz_t.getCPtr(x), SWIGTYPE_p_flint_bitcnt_t.getCPtr(r), SWIGTYPE_p_slong.getCPtr(N));
  }

  public static void arb_atan_arf_bb(arb_struct z, SWIGTYPE_p_arf_t x, SWIGTYPE_p_slong prec) {
    arblibJNI.arb_atan_arf_bb(arb_struct.getCPtr(z), z, SWIGTYPE_p_arf_t.getCPtr(x), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static SWIGTYPE_p_slong arb_allocated_bytes(arb_struct x) {
    return new SWIGTYPE_p_slong(arblibJNI.arb_allocated_bytes(arb_struct.getCPtr(x), x), true);
  }

  public static SWIGTYPE_p_slong _arb_vec_allocated_bytes(arb_struct vec, SWIGTYPE_p_slong len) {
    return new SWIGTYPE_p_slong(arblibJNI._arb_vec_allocated_bytes(arb_struct.getCPtr(vec), vec, SWIGTYPE_p_slong.getCPtr(len)), true);
  }

  public static double _arb_vec_estimate_allocated_bytes(SWIGTYPE_p_slong len, SWIGTYPE_p_slong prec) {
    return arblibJNI._arb_vec_estimate_allocated_bytes(SWIGTYPE_p_slong.getCPtr(len), SWIGTYPE_p_slong.getCPtr(prec));
  }

  public static int arb_load_str(arb_struct res, String data) {
    return arblibJNI.arb_load_str(arb_struct.getCPtr(res), res, data);
  }

  public static String arb_dump_str(arb_struct x) {
    return arblibJNI.arb_dump_str(arb_struct.getCPtr(x), x);
  }

  public static int arb_load_file(arb_struct res, SWIGTYPE_p_FILE stream) {
    return arblibJNI.arb_load_file(arb_struct.getCPtr(res), res, SWIGTYPE_p_FILE.getCPtr(stream));
  }

  public static int arb_dump_file(SWIGTYPE_p_FILE stream, arb_struct x) {
    return arblibJNI.arb_dump_file(SWIGTYPE_p_FILE.getCPtr(stream), arb_struct.getCPtr(x), x);
  }

}
