/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class arblibJNI {
  public final static native void acb_struct_real_set(long jarg1, acb_struct jarg1_, long jarg2);
  public final static native long acb_struct_real_get(long jarg1, acb_struct jarg1_);
  public final static native void acb_struct_imag_set(long jarg1, acb_struct jarg1_, long jarg2);
  public final static native long acb_struct_imag_get(long jarg1, acb_struct jarg1_);
  public final static native long new_acb_struct();
  public final static native void delete_acb_struct(long jarg1);
  public final static native void acb_set_d(long jarg1, double jarg2);
  public final static native void acb_dirichlet_hardy_z(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, long jarg6);
}
