/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class arf_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected arf_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(arf_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_arf_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExp(SWIGTYPE_p_fmpz value) {
    arblibJNI.arf_struct_exp_set(swigCPtr, this, SWIGTYPE_p_fmpz.getCPtr(value));
  }

  public SWIGTYPE_p_fmpz getExp() {
    return new SWIGTYPE_p_fmpz(arblibJNI.arf_struct_exp_get(swigCPtr, this), true);
  }

  public void setSize(int value) {
    arblibJNI.arf_struct_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return arblibJNI.arf_struct_size_get(swigCPtr, this);
  }

  public void setD(mantissa_struct value) {
    arblibJNI.arf_struct_d_set(swigCPtr, this, mantissa_struct.getCPtr(value), value);
  }

  public mantissa_struct getD() {
    long cPtr = arblibJNI.arf_struct_d_get(swigCPtr, this);
    return (cPtr == 0) ? null : new mantissa_struct(cPtr, false);
  }

  public arf_struct() {
    this(arblibJNI.new_arf_struct(), true);
  }

}
