/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class clone_args {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected clone_args(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(clone_args obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_clone_args(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlags(java.math.BigInteger value) {
    arblibJNI.clone_args_flags_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getFlags() {
    return arblibJNI.clone_args_flags_get(swigCPtr, this);
  }

  public void setPidfd(java.math.BigInteger value) {
    arblibJNI.clone_args_pidfd_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getPidfd() {
    return arblibJNI.clone_args_pidfd_get(swigCPtr, this);
  }

  public void setChild_tid(java.math.BigInteger value) {
    arblibJNI.clone_args_child_tid_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getChild_tid() {
    return arblibJNI.clone_args_child_tid_get(swigCPtr, this);
  }

  public void setParent_tid(java.math.BigInteger value) {
    arblibJNI.clone_args_parent_tid_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getParent_tid() {
    return arblibJNI.clone_args_parent_tid_get(swigCPtr, this);
  }

  public void setExit_signal(java.math.BigInteger value) {
    arblibJNI.clone_args_exit_signal_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getExit_signal() {
    return arblibJNI.clone_args_exit_signal_get(swigCPtr, this);
  }

  public void setStack(java.math.BigInteger value) {
    arblibJNI.clone_args_stack_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getStack() {
    return arblibJNI.clone_args_stack_get(swigCPtr, this);
  }

  public void setStack_size(java.math.BigInteger value) {
    arblibJNI.clone_args_stack_size_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getStack_size() {
    return arblibJNI.clone_args_stack_size_get(swigCPtr, this);
  }

  public void setTls(java.math.BigInteger value) {
    arblibJNI.clone_args_tls_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTls() {
    return arblibJNI.clone_args_tls_get(swigCPtr, this);
  }

  public void setSet_tid(java.math.BigInteger value) {
    arblibJNI.clone_args_set_tid_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSet_tid() {
    return arblibJNI.clone_args_set_tid_get(swigCPtr, this);
  }

  public void setSet_tid_size(java.math.BigInteger value) {
    arblibJNI.clone_args_set_tid_size_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSet_tid_size() {
    return arblibJNI.clone_args_set_tid_size_get(swigCPtr, this);
  }

  public void setCgroup(java.math.BigInteger value) {
    arblibJNI.clone_args_cgroup_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getCgroup() {
    return arblibJNI.clone_args_cgroup_get(swigCPtr, this);
  }

  public clone_args() {
    this(arblibJNI.new_clone_args(), true);
  }

}
