/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class col_hash_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected col_hash_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(col_hash_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_col_hash_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCol(long value) {
    arblibJNI.col_hash_t_col_set(swigCPtr, this, value);
  }

  public long getCol() {
    return arblibJNI.col_hash_t_col_get(swigCPtr, this);
  }

  public void setHash(long value) {
    arblibJNI.col_hash_t_hash_set(swigCPtr, this, value);
  }

  public long getHash() {
    return arblibJNI.col_hash_t_hash_get(swigCPtr, this);
  }

  public col_hash_t() {
    this(arblibJNI.new_col_hash_t(), true);
  }

}
