/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dirichlet_group_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dirichlet_group_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dirichlet_group_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dirichlet_group_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQ(long value) {
    arblibJNI.dirichlet_group_struct_q_set(swigCPtr, this, value);
  }

  public long getQ() {
    return arblibJNI.dirichlet_group_struct_q_get(swigCPtr, this);
  }

  public void setQ_even(long value) {
    arblibJNI.dirichlet_group_struct_q_even_set(swigCPtr, this, value);
  }

  public long getQ_even() {
    return arblibJNI.dirichlet_group_struct_q_even_get(swigCPtr, this);
  }

  public void setMod(SWIGTYPE_p_nmod_t value) {
    arblibJNI.dirichlet_group_struct_mod_set(swigCPtr, this, SWIGTYPE_p_nmod_t.getCPtr(value));
  }

  public SWIGTYPE_p_nmod_t getMod() {
    return new SWIGTYPE_p_nmod_t(arblibJNI.dirichlet_group_struct_mod_get(swigCPtr, this), true);
  }

  public void setRad_q(long value) {
    arblibJNI.dirichlet_group_struct_rad_q_set(swigCPtr, this, value);
  }

  public long getRad_q() {
    return arblibJNI.dirichlet_group_struct_rad_q_get(swigCPtr, this);
  }

  public void setPhi_q(long value) {
    arblibJNI.dirichlet_group_struct_phi_q_set(swigCPtr, this, value);
  }

  public long getPhi_q() {
    return arblibJNI.dirichlet_group_struct_phi_q_get(swigCPtr, this);
  }

  public void setNeven(int value) {
    arblibJNI.dirichlet_group_struct_neven_set(swigCPtr, this, value);
  }

  public int getNeven() {
    return arblibJNI.dirichlet_group_struct_neven_get(swigCPtr, this);
  }

  public void setNum(int value) {
    arblibJNI.dirichlet_group_struct_num_set(swigCPtr, this, value);
  }

  public int getNum() {
    return arblibJNI.dirichlet_group_struct_num_get(swigCPtr, this);
  }

  public void setExpo(long value) {
    arblibJNI.dirichlet_group_struct_expo_set(swigCPtr, this, value);
  }

  public long getExpo() {
    return arblibJNI.dirichlet_group_struct_expo_get(swigCPtr, this);
  }

  public void setP(dirichlet_prime_group_struct value) {
    arblibJNI.dirichlet_group_struct_P_set(swigCPtr, this, dirichlet_prime_group_struct.getCPtr(value), value);
  }

  public dirichlet_prime_group_struct getP() {
    long cPtr = arblibJNI.dirichlet_group_struct_P_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dirichlet_prime_group_struct(cPtr, false);
  }

  public void setGenerators(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.dirichlet_group_struct_generators_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getGenerators() {
    long cPtr = arblibJNI.dirichlet_group_struct_generators_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setPHI(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.dirichlet_group_struct_PHI_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getPHI() {
    long cPtr = arblibJNI.dirichlet_group_struct_PHI_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public dirichlet_group_struct() {
    this(arblibJNI.new_dirichlet_group_struct(), true);
  }

}
