/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dirichlet_char_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dirichlet_char_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dirichlet_char_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dirichlet_char_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setN(SWIGTYPE_p_ulong value) {
    arblibJNI.dirichlet_char_struct_n_set(swigCPtr, this, SWIGTYPE_p_ulong.getCPtr(value));
  }

  public SWIGTYPE_p_ulong getN() {
    return new SWIGTYPE_p_ulong(arblibJNI.dirichlet_char_struct_n_get(swigCPtr, this), true);
  }

  public void setLog(SWIGTYPE_p_ulong value) {
    arblibJNI.dirichlet_char_struct_log_set(swigCPtr, this, SWIGTYPE_p_ulong.getCPtr(value));
  }

  public SWIGTYPE_p_ulong getLog() {
    long cPtr = arblibJNI.dirichlet_char_struct_log_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ulong(cPtr, false);
  }

  public dirichlet_char_struct() {
    this(arblibJNI.new_dirichlet_char_struct(), true);
  }

}
