/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dlog_precomp_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dlog_precomp_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dlog_precomp_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dlog_precomp_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    arblibJNI.dlog_precomp_struct_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return arblibJNI.dlog_precomp_struct_type_get(swigCPtr, this);
  }

  public void setCost(long value) {
    arblibJNI.dlog_precomp_struct_cost_set(swigCPtr, this, value);
  }

  public long getCost() {
    return arblibJNI.dlog_precomp_struct_cost_get(swigCPtr, this);
  }

  public dlog_precomp_struct() {
    this(arblibJNI.new_dlog_precomp_struct(), true);
  }

}
