/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dlog_1modpe_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dlog_1modpe_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dlog_1modpe_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dlog_1modpe_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInv1p(long value) {
    arblibJNI.dlog_1modpe_struct_inv1p_set(swigCPtr, this, value);
  }

  public long getInv1p() {
    return arblibJNI.dlog_1modpe_struct_inv1p_get(swigCPtr, this);
  }

  public void setInvloga1(long value) {
    arblibJNI.dlog_1modpe_struct_invloga1_set(swigCPtr, this, value);
  }

  public long getInvloga1() {
    return arblibJNI.dlog_1modpe_struct_invloga1_get(swigCPtr, this);
  }

  public dlog_1modpe_struct() {
    this(arblibJNI.new_dlog_1modpe_struct(), true);
  }

}
