/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dlog_modpe_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dlog_modpe_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dlog_modpe_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dlog_modpe_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setP(long value) {
    arblibJNI.dlog_modpe_struct_p_set(swigCPtr, this, value);
  }

  public long getP() {
    return arblibJNI.dlog_modpe_struct_p_get(swigCPtr, this);
  }

  public void setE(long value) {
    arblibJNI.dlog_modpe_struct_e_set(swigCPtr, this, value);
  }

  public long getE() {
    return arblibJNI.dlog_modpe_struct_e_get(swigCPtr, this);
  }

  public void setPe1(long value) {
    arblibJNI.dlog_modpe_struct_pe1_set(swigCPtr, this, value);
  }

  public long getPe1() {
    return arblibJNI.dlog_modpe_struct_pe1_get(swigCPtr, this);
  }

  public void setInva(long value) {
    arblibJNI.dlog_modpe_struct_inva_set(swigCPtr, this, value);
  }

  public long getInva() {
    return arblibJNI.dlog_modpe_struct_inva_get(swigCPtr, this);
  }

  public void setPe(nmod_t value) {
    arblibJNI.dlog_modpe_struct_pe_set(swigCPtr, this, nmod_t.getCPtr(value), value);
  }

  public nmod_t getPe() {
    long cPtr = arblibJNI.dlog_modpe_struct_pe_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_t(cPtr, false);
  }

  public void setModp(dlog_precomp_struct value) {
    arblibJNI.dlog_modpe_struct_modp_set(swigCPtr, this, dlog_precomp_struct.getCPtr(value), value);
  }

  public dlog_precomp_struct getModp() {
    long cPtr = arblibJNI.dlog_modpe_struct_modp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dlog_precomp_struct(cPtr, false);
  }

  public void setModpe(dlog_1modpe_struct value) {
    arblibJNI.dlog_modpe_struct_modpe_set(swigCPtr, this, dlog_1modpe_struct.getCPtr(value), value);
  }

  public dlog_1modpe_struct getModpe() {
    long cPtr = arblibJNI.dlog_modpe_struct_modpe_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dlog_1modpe_struct(cPtr, false);
  }

  public dlog_modpe_struct() {
    this(arblibJNI.new_dlog_modpe_struct(), true);
  }

}
