/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dlog_power_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dlog_power_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dlog_power_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dlog_power_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMod(nmod_t value) {
    arblibJNI.dlog_power_struct_mod_set(swigCPtr, this, nmod_t.getCPtr(value), value);
  }

  public nmod_t getMod() {
    long cPtr = arblibJNI.dlog_power_struct_mod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_t(cPtr, false);
  }

  public void setP(long value) {
    arblibJNI.dlog_power_struct_p_set(swigCPtr, this, value);
  }

  public long getP() {
    return arblibJNI.dlog_power_struct_p_get(swigCPtr, this);
  }

  public void setE(long value) {
    arblibJNI.dlog_power_struct_e_set(swigCPtr, this, value);
  }

  public long getE() {
    return arblibJNI.dlog_power_struct_e_get(swigCPtr, this);
  }

  public void setApk(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.dlog_power_struct_apk_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getApk() {
    long cPtr = arblibJNI.dlog_power_struct_apk_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setPre(dlog_precomp_struct value) {
    arblibJNI.dlog_power_struct_pre_set(swigCPtr, this, dlog_precomp_struct.getCPtr(value), value);
  }

  public dlog_precomp_struct getPre() {
    long cPtr = arblibJNI.dlog_power_struct_pre_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dlog_precomp_struct(cPtr, false);
  }

  public dlog_power_struct() {
    this(arblibJNI.new_dlog_power_struct(), true);
  }

}
