/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dlog_rho_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dlog_rho_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dlog_rho_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dlog_rho_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setA(long value) {
    arblibJNI.dlog_rho_struct_a_set(swigCPtr, this, value);
  }

  public long getA() {
    return arblibJNI.dlog_rho_struct_a_get(swigCPtr, this);
  }

  public void setN(nmod_t value) {
    arblibJNI.dlog_rho_struct_n_set(swigCPtr, this, nmod_t.getCPtr(value), value);
  }

  public nmod_t getN() {
    long cPtr = arblibJNI.dlog_rho_struct_n_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_t(cPtr, false);
  }

  public void setMod(nmod_t value) {
    arblibJNI.dlog_rho_struct_mod_set(swigCPtr, this, nmod_t.getCPtr(value), value);
  }

  public nmod_t getMod() {
    long cPtr = arblibJNI.dlog_rho_struct_mod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_t(cPtr, false);
  }

  public void setNisprime(int value) {
    arblibJNI.dlog_rho_struct_nisprime_set(swigCPtr, this, value);
  }

  public int getNisprime() {
    return arblibJNI.dlog_rho_struct_nisprime_get(swigCPtr, this);
  }

  public dlog_rho_struct() {
    this(arblibJNI.new_dlog_rho_struct(), true);
  }

}
