/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dlog_bsgs_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dlog_bsgs_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dlog_bsgs_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dlog_bsgs_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMod(nmod_t value) {
    arblibJNI.dlog_bsgs_struct_mod_set(swigCPtr, this, nmod_t.getCPtr(value), value);
  }

  public nmod_t getMod() {
    long cPtr = arblibJNI.dlog_bsgs_struct_mod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_t(cPtr, false);
  }

  public void setM(long value) {
    arblibJNI.dlog_bsgs_struct_m_set(swigCPtr, this, value);
  }

  public long getM() {
    return arblibJNI.dlog_bsgs_struct_m_get(swigCPtr, this);
  }

  public void setAm(long value) {
    arblibJNI.dlog_bsgs_struct_am_set(swigCPtr, this, value);
  }

  public long getAm() {
    return arblibJNI.dlog_bsgs_struct_am_get(swigCPtr, this);
  }

  public void setG(long value) {
    arblibJNI.dlog_bsgs_struct_g_set(swigCPtr, this, value);
  }

  public long getG() {
    return arblibJNI.dlog_bsgs_struct_g_get(swigCPtr, this);
  }

  public void setTable(apow_t value) {
    arblibJNI.dlog_bsgs_struct_table_set(swigCPtr, this, apow_t.getCPtr(value), value);
  }

  public apow_t getTable() {
    long cPtr = arblibJNI.dlog_bsgs_struct_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new apow_t(cPtr, false);
  }

  public dlog_bsgs_struct() {
    this(arblibJNI.new_dlog_bsgs_struct(), true);
  }

}
