/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class dlog_table_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dlog_table_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dlog_table_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_dlog_table_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMod(long value) {
    arblibJNI.dlog_table_struct_mod_set(swigCPtr, this, value);
  }

  public long getMod() {
    return arblibJNI.dlog_table_struct_mod_get(swigCPtr, this);
  }

  public void setTable(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.dlog_table_struct_table_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getTable() {
    long cPtr = arblibJNI.dlog_table_struct_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public dlog_table_struct() {
    this(arblibJNI.new_dlog_table_struct(), true);
  }

}
