/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fd_set {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fd_set(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fd_set obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fd_set(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__fds_bits(SWIGTYPE_p_long value) {
    arblibJNI.fd_set___fds_bits_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long get__fds_bits() {
    long cPtr = arblibJNI.fd_set___fds_bits_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public fd_set() {
    this(arblibJNI.new_fd_set(), true);
  }

}
