/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public final class flint_err_t {
  public final static flint_err_t FLINT_ERROR = new flint_err_t("FLINT_ERROR");
  public final static flint_err_t FLINT_IMPINV = new flint_err_t("FLINT_IMPINV");
  public final static flint_err_t FLINT_DOMERR = new flint_err_t("FLINT_DOMERR");
  public final static flint_err_t FLINT_DIVZERO = new flint_err_t("FLINT_DIVZERO");
  public final static flint_err_t FLINT_EXPOF = new flint_err_t("FLINT_EXPOF");
  public final static flint_err_t FLINT_INEXACT = new flint_err_t("FLINT_INEXACT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static flint_err_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + flint_err_t.class + " with value " + swigValue);
  }

  private flint_err_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private flint_err_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private flint_err_t(String swigName, flint_err_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static flint_err_t[] swigValues = { FLINT_ERROR, FLINT_IMPINV, FLINT_DOMERR, FLINT_DIVZERO, FLINT_EXPOF, FLINT_INEXACT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

