/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class flint_rand_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected flint_rand_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(flint_rand_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_flint_rand_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGmp_state(__gmp_randstate_struct value) {
    arblibJNI.flint_rand_s_gmp_state_set(swigCPtr, this, __gmp_randstate_struct.getCPtr(value), value);
  }

  public __gmp_randstate_struct getGmp_state() {
    long cPtr = arblibJNI.flint_rand_s_gmp_state_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __gmp_randstate_struct(cPtr, false);
  }

  public void setGmp_init(int value) {
    arblibJNI.flint_rand_s_gmp_init_set(swigCPtr, this, value);
  }

  public int getGmp_init() {
    return arblibJNI.flint_rand_s_gmp_init_get(swigCPtr, this);
  }

  public void set__randval(long value) {
    arblibJNI.flint_rand_s___randval_set(swigCPtr, this, value);
  }

  public long get__randval() {
    return arblibJNI.flint_rand_s___randval_get(swigCPtr, this);
  }

  public void set__randval2(long value) {
    arblibJNI.flint_rand_s___randval2_set(swigCPtr, this, value);
  }

  public long get__randval2() {
    return arblibJNI.flint_rand_s___randval2_get(swigCPtr, this);
  }

  public flint_rand_s() {
    this(arblibJNI.new_flint_rand_s(), true);
  }

}
