/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpq {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpq(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpq obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpq(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum(int value) {
    arblibJNI.fmpq_num_set(swigCPtr, this, value);
  }

  public int getNum() {
    return arblibJNI.fmpq_num_get(swigCPtr, this);
  }

  public void setDen(int value) {
    arblibJNI.fmpq_den_set(swigCPtr, this, value);
  }

  public int getDen() {
    return arblibJNI.fmpq_den_get(swigCPtr, this);
  }

  public fmpq() {
    this(arblibJNI.new_fmpq(), true);
  }

}
