/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpq_poly_powers_precomp_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpq_poly_powers_precomp_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpq_poly_powers_precomp_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpq_poly_powers_precomp_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPowers(fmpq_poly_struct value) {
    arblibJNI.fmpq_poly_powers_precomp_struct_powers_set(swigCPtr, this, fmpq_poly_struct.getCPtr(value), value);
  }

  public fmpq_poly_struct getPowers() {
    long cPtr = arblibJNI.fmpq_poly_powers_precomp_struct_powers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fmpq_poly_struct(cPtr, false);
  }

  public void setLen(int value) {
    arblibJNI.fmpq_poly_powers_precomp_struct_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return arblibJNI.fmpq_poly_powers_precomp_struct_len_get(swigCPtr, this);
  }

  public fmpq_poly_powers_precomp_struct() {
    this(arblibJNI.new_fmpq_poly_powers_precomp_struct(), true);
  }

}
