/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpq_poly_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpq_poly_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpq_poly_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpq_poly_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCoeffs(SWIGTYPE_p_long value) {
    arblibJNI.fmpq_poly_struct_coeffs_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getCoeffs() {
    long cPtr = arblibJNI.fmpq_poly_struct_coeffs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setDen(SWIGTYPE_p_long value) {
    arblibJNI.fmpq_poly_struct_den_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getDen() {
    long cPtr = arblibJNI.fmpq_poly_struct_den_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setAlloc(int value) {
    arblibJNI.fmpq_poly_struct_alloc_set(swigCPtr, this, value);
  }

  public int getAlloc() {
    return arblibJNI.fmpq_poly_struct_alloc_get(swigCPtr, this);
  }

  public void setLength(int value) {
    arblibJNI.fmpq_poly_struct_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return arblibJNI.fmpq_poly_struct_length_get(swigCPtr, this);
  }

  public fmpq_poly_struct() {
    this(arblibJNI.new_fmpq_poly_struct(), true);
  }

}
