/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpr_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpr_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpr_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpr_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMan(int value) {
    arblibJNI.fmpr_struct_man_set(swigCPtr, this, value);
  }

  public int getMan() {
    return arblibJNI.fmpr_struct_man_get(swigCPtr, this);
  }

  public void setExp(int value) {
    arblibJNI.fmpr_struct_exp_set(swigCPtr, this, value);
  }

  public int getExp() {
    return arblibJNI.fmpr_struct_exp_get(swigCPtr, this);
  }

  public fmpr_struct() {
    this(arblibJNI.new_fmpr_struct(), true);
  }

}
