/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpz_comb_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpz_comb_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpz_comb_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpz_comb_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPrimes(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.fmpz_comb_struct_primes_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getPrimes() {
    long cPtr = arblibJNI.fmpz_comb_struct_primes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setNum_primes(int value) {
    arblibJNI.fmpz_comb_struct_num_primes_set(swigCPtr, this, value);
  }

  public int getNum_primes() {
    return arblibJNI.fmpz_comb_struct_num_primes_get(swigCPtr, this);
  }

  public void setN(int value) {
    arblibJNI.fmpz_comb_struct_n_set(swigCPtr, this, value);
  }

  public int getN() {
    return arblibJNI.fmpz_comb_struct_n_get(swigCPtr, this);
  }

  public void setComb(SWIGTYPE_p_p_long value) {
    arblibJNI.fmpz_comb_struct_comb_set(swigCPtr, this, SWIGTYPE_p_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_p_long getComb() {
    long cPtr = arblibJNI.fmpz_comb_struct_comb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_long(cPtr, false);
  }

  public void setRes(SWIGTYPE_p_p_long value) {
    arblibJNI.fmpz_comb_struct_res_set(swigCPtr, this, SWIGTYPE_p_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_p_long getRes() {
    long cPtr = arblibJNI.fmpz_comb_struct_res_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_long(cPtr, false);
  }

  public void setMod(nmod_t value) {
    arblibJNI.fmpz_comb_struct_mod_set(swigCPtr, this, nmod_t.getCPtr(value), value);
  }

  public nmod_t getMod() {
    long cPtr = arblibJNI.fmpz_comb_struct_mod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_t(cPtr, false);
  }

  public fmpz_comb_struct() {
    this(arblibJNI.new_fmpz_comb_struct(), true);
  }

}
