/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpz_block_header_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpz_block_header_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpz_block_header_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpz_block_header_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(int value) {
    arblibJNI.fmpz_block_header_s_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return arblibJNI.fmpz_block_header_s_count_get(swigCPtr, this);
  }

  public void setThread(long value) {
    arblibJNI.fmpz_block_header_s_thread_set(swigCPtr, this, value);
  }

  public long getThread() {
    return arblibJNI.fmpz_block_header_s_thread_get(swigCPtr, this);
  }

  public void setAddress(SWIGTYPE_p_void value) {
    arblibJNI.fmpz_block_header_s_address_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getAddress() {
    long cPtr = arblibJNI.fmpz_block_header_s_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public fmpz_block_header_s() {
    this(arblibJNI.new_fmpz_block_header_s(), true);
  }

}
