/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpz_poly_mul_precache_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpz_poly_mul_precache_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpz_poly_mul_precache_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpz_poly_mul_precache_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setJj(SWIGTYPE_p_p_unsigned_long value) {
    arblibJNI.fmpz_poly_mul_precache_struct_jj_set(swigCPtr, this, SWIGTYPE_p_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_p_unsigned_long getJj() {
    long cPtr = arblibJNI.fmpz_poly_mul_precache_struct_jj_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_unsigned_long(cPtr, false);
  }

  public void setN(int value) {
    arblibJNI.fmpz_poly_mul_precache_struct_n_set(swigCPtr, this, value);
  }

  public int getN() {
    return arblibJNI.fmpz_poly_mul_precache_struct_n_get(swigCPtr, this);
  }

  public void setLen2(int value) {
    arblibJNI.fmpz_poly_mul_precache_struct_len2_set(swigCPtr, this, value);
  }

  public int getLen2() {
    return arblibJNI.fmpz_poly_mul_precache_struct_len2_get(swigCPtr, this);
  }

  public void setLoglen(int value) {
    arblibJNI.fmpz_poly_mul_precache_struct_loglen_set(swigCPtr, this, value);
  }

  public int getLoglen() {
    return arblibJNI.fmpz_poly_mul_precache_struct_loglen_get(swigCPtr, this);
  }

  public void setBits2(int value) {
    arblibJNI.fmpz_poly_mul_precache_struct_bits2_set(swigCPtr, this, value);
  }

  public int getBits2() {
    return arblibJNI.fmpz_poly_mul_precache_struct_bits2_get(swigCPtr, this);
  }

  public void setLimbs(int value) {
    arblibJNI.fmpz_poly_mul_precache_struct_limbs_set(swigCPtr, this, value);
  }

  public int getLimbs() {
    return arblibJNI.fmpz_poly_mul_precache_struct_limbs_get(swigCPtr, this);
  }

  public void setPoly2(fmpz_poly_struct value) {
    arblibJNI.fmpz_poly_mul_precache_struct_poly2_set(swigCPtr, this, fmpz_poly_struct.getCPtr(value), value);
  }

  public fmpz_poly_struct getPoly2() {
    long cPtr = arblibJNI.fmpz_poly_mul_precache_struct_poly2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fmpz_poly_struct(cPtr, false);
  }

  public fmpz_poly_mul_precache_struct() {
    this(arblibJNI.new_fmpz_poly_mul_precache_struct(), true);
  }

}
