/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpz_preinvn_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpz_preinvn_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpz_preinvn_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpz_preinvn_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDinv(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.fmpz_preinvn_struct_dinv_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getDinv() {
    long cPtr = arblibJNI.fmpz_preinvn_struct_dinv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setN(int value) {
    arblibJNI.fmpz_preinvn_struct_n_set(swigCPtr, this, value);
  }

  public int getN() {
    return arblibJNI.fmpz_preinvn_struct_n_get(swigCPtr, this);
  }

  public void setNorm(long value) {
    arblibJNI.fmpz_preinvn_struct_norm_set(swigCPtr, this, value);
  }

  public long getNorm() {
    return arblibJNI.fmpz_preinvn_struct_norm_get(swigCPtr, this);
  }

  public fmpz_preinvn_struct() {
    this(arblibJNI.new_fmpz_preinvn_struct(), true);
  }

}
