/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpz_poly_factor_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpz_poly_factor_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpz_poly_factor_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpz_poly_factor_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setC(int value) {
    arblibJNI.fmpz_poly_factor_struct_c_set(swigCPtr, this, value);
  }

  public int getC() {
    return arblibJNI.fmpz_poly_factor_struct_c_get(swigCPtr, this);
  }

  public void setP(fmpz_poly_struct value) {
    arblibJNI.fmpz_poly_factor_struct_p_set(swigCPtr, this, fmpz_poly_struct.getCPtr(value), value);
  }

  public fmpz_poly_struct getP() {
    long cPtr = arblibJNI.fmpz_poly_factor_struct_p_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fmpz_poly_struct(cPtr, false);
  }

  public void setExp(SWIGTYPE_p_long value) {
    arblibJNI.fmpz_poly_factor_struct_exp_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getExp() {
    long cPtr = arblibJNI.fmpz_poly_factor_struct_exp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setNum(int value) {
    arblibJNI.fmpz_poly_factor_struct_num_set(swigCPtr, this, value);
  }

  public int getNum() {
    return arblibJNI.fmpz_poly_factor_struct_num_get(swigCPtr, this);
  }

  public void setAlloc(int value) {
    arblibJNI.fmpz_poly_factor_struct_alloc_set(swigCPtr, this, value);
  }

  public int getAlloc() {
    return arblibJNI.fmpz_poly_factor_struct_alloc_get(swigCPtr, this);
  }

  public fmpz_poly_factor_struct() {
    this(arblibJNI.new_fmpz_poly_factor_struct(), true);
  }

}
