/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class fmpz_comb_temp_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fmpz_comb_temp_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fmpz_comb_temp_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_fmpz_comb_temp_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setN(int value) {
    arblibJNI.fmpz_comb_temp_struct_n_set(swigCPtr, this, value);
  }

  public int getN() {
    return arblibJNI.fmpz_comb_temp_struct_n_get(swigCPtr, this);
  }

  public void setComb_temp(SWIGTYPE_p_p_long value) {
    arblibJNI.fmpz_comb_temp_struct_comb_temp_set(swigCPtr, this, SWIGTYPE_p_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_p_long getComb_temp() {
    long cPtr = arblibJNI.fmpz_comb_temp_struct_comb_temp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_long(cPtr, false);
  }

  public void setTemp(SWIGTYPE_p_long value) {
    arblibJNI.fmpz_comb_temp_struct_temp_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getTemp() {
    long cPtr = arblibJNI.fmpz_comb_temp_struct_temp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public void setTemp2(SWIGTYPE_p_long value) {
    arblibJNI.fmpz_comb_temp_struct_temp2_set(swigCPtr, this, SWIGTYPE_p_long.getCPtr(value));
  }

  public SWIGTYPE_p_long getTemp2() {
    long cPtr = arblibJNI.fmpz_comb_temp_struct_temp2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public fmpz_comb_temp_struct() {
    this(arblibJNI.new_fmpz_comb_temp_struct(), true);
  }

}
