/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public final class gmp_randalg_t {
  public final static gmp_randalg_t GMP_RAND_ALG_DEFAULT = new gmp_randalg_t("GMP_RAND_ALG_DEFAULT", arblibJNI.GMP_RAND_ALG_DEFAULT_get());
  public final static gmp_randalg_t GMP_RAND_ALG_LC = new gmp_randalg_t("GMP_RAND_ALG_LC", arblibJNI.GMP_RAND_ALG_LC_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static gmp_randalg_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + gmp_randalg_t.class + " with value " + swigValue);
  }

  private gmp_randalg_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private gmp_randalg_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private gmp_randalg_t(String swigName, gmp_randalg_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static gmp_randalg_t[] swigValues = { GMP_RAND_ALG_DEFAULT, GMP_RAND_ALG_LC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

