/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public final class idtype_t {
  public final static idtype_t P_ALL = new idtype_t("P_ALL");
  public final static idtype_t P_PID = new idtype_t("P_PID");
  public final static idtype_t P_PGID = new idtype_t("P_PGID");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static idtype_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + idtype_t.class + " with value " + swigValue);
  }

  private idtype_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private idtype_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private idtype_t(String swigName, idtype_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static idtype_t[] swigValues = { P_ALL, P_PID, P_PGID };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

