/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class itimerspec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected itimerspec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(itimerspec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_itimerspec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIt_interval(timespec value) {
    arblibJNI.itimerspec_it_interval_set(swigCPtr, this, timespec.getCPtr(value), value);
  }

  public timespec getIt_interval() {
    long cPtr = arblibJNI.itimerspec_it_interval_get(swigCPtr, this);
    return (cPtr == 0) ? null : new timespec(cPtr, false);
  }

  public void setIt_value(timespec value) {
    arblibJNI.itimerspec_it_value_set(swigCPtr, this, timespec.getCPtr(value), value);
  }

  public timespec getIt_value() {
    long cPtr = arblibJNI.itimerspec_it_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new timespec(cPtr, false);
  }

  public itimerspec() {
    this(arblibJNI.new_itimerspec(), true);
  }

}
