/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class itimerval {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected itimerval(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(itimerval obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_itimerval(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIt_interval(timeval value) {
    arblibJNI.itimerval_it_interval_set(swigCPtr, this, timeval.getCPtr(value), value);
  }

  public timeval getIt_interval() {
    long cPtr = arblibJNI.itimerval_it_interval_get(swigCPtr, this);
    return (cPtr == 0) ? null : new timeval(cPtr, false);
  }

  public void setIt_value(timeval value) {
    arblibJNI.itimerval_it_value_set(swigCPtr, this, timeval.getCPtr(value), value);
  }

  public timeval getIt_value() {
    long cPtr = arblibJNI.itimerval_it_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new timeval(cPtr, false);
  }

  public itimerval() {
    this(arblibJNI.new_itimerval(), true);
  }

}
