/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class ldiv_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ldiv_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ldiv_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_ldiv_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQuot(int value) {
    arblibJNI.ldiv_t_quot_set(swigCPtr, this, value);
  }

  public int getQuot() {
    return arblibJNI.ldiv_t_quot_get(swigCPtr, this);
  }

  public void setRem(int value) {
    arblibJNI.ldiv_t_rem_set(swigCPtr, this, value);
  }

  public int getRem() {
    return arblibJNI.ldiv_t_rem_get(swigCPtr, this);
  }

  public ldiv_t() {
    this(arblibJNI.new_ldiv_t(), true);
  }

}
