/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class mantissa_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected mantissa_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mantissa_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_mantissa_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNoptr(mantissa_noptr_struct value) {
    arblibJNI.mantissa_struct_noptr_set(swigCPtr, this, mantissa_noptr_struct.getCPtr(value), value);
  }

  public mantissa_noptr_struct getNoptr() {
    long cPtr = arblibJNI.mantissa_struct_noptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new mantissa_noptr_struct(cPtr, false);
  }

  public void setPtr(mantissa_ptr_struct value) {
    arblibJNI.mantissa_struct_ptr_set(swigCPtr, this, mantissa_ptr_struct.getCPtr(value), value);
  }

  public mantissa_ptr_struct getPtr() {
    long cPtr = arblibJNI.mantissa_struct_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new mantissa_ptr_struct(cPtr, false);
  }

  public mantissa_struct() {
    this(arblibJNI.new_mantissa_struct(), true);
  }

}
