/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class mantissa_ptr_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected mantissa_ptr_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mantissa_ptr_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_mantissa_ptr_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAlloc(SWIGTYPE_p_mp_size_t value) {
    arblibJNI.mantissa_ptr_struct_alloc_set(swigCPtr, this, SWIGTYPE_p_mp_size_t.getCPtr(value));
  }

  public SWIGTYPE_p_mp_size_t getAlloc() {
    return new SWIGTYPE_p_mp_size_t(arblibJNI.mantissa_ptr_struct_alloc_get(swigCPtr, this), true);
  }

  public void setD(SWIGTYPE_p_mp_ptr value) {
    arblibJNI.mantissa_ptr_struct_d_set(swigCPtr, this, SWIGTYPE_p_mp_ptr.getCPtr(value));
  }

  public SWIGTYPE_p_mp_ptr getD() {
    return new SWIGTYPE_p_mp_ptr(arblibJNI.mantissa_ptr_struct_d_get(swigCPtr, this), true);
  }

  public mantissa_ptr_struct() {
    this(arblibJNI.new_mantissa_ptr_struct(), true);
  }

}
