/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public final class mpfr_kind_t {
  public final static mpfr_kind_t MPFR_NAN_KIND = new mpfr_kind_t("MPFR_NAN_KIND", arblibJNI.MPFR_NAN_KIND_get());
  public final static mpfr_kind_t MPFR_INF_KIND = new mpfr_kind_t("MPFR_INF_KIND", arblibJNI.MPFR_INF_KIND_get());
  public final static mpfr_kind_t MPFR_ZERO_KIND = new mpfr_kind_t("MPFR_ZERO_KIND", arblibJNI.MPFR_ZERO_KIND_get());
  public final static mpfr_kind_t MPFR_REGULAR_KIND = new mpfr_kind_t("MPFR_REGULAR_KIND", arblibJNI.MPFR_REGULAR_KIND_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mpfr_kind_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mpfr_kind_t.class + " with value " + swigValue);
  }

  private mpfr_kind_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mpfr_kind_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mpfr_kind_t(String swigName, mpfr_kind_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mpfr_kind_t[] swigValues = { MPFR_NAN_KIND, MPFR_INF_KIND, MPFR_ZERO_KIND, MPFR_REGULAR_KIND };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

