/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public final class mpfr_free_cache_t {
  public final static mpfr_free_cache_t MPFR_FREE_LOCAL_CACHE = new mpfr_free_cache_t("MPFR_FREE_LOCAL_CACHE", arblibJNI.MPFR_FREE_LOCAL_CACHE_get());
  public final static mpfr_free_cache_t MPFR_FREE_GLOBAL_CACHE = new mpfr_free_cache_t("MPFR_FREE_GLOBAL_CACHE", arblibJNI.MPFR_FREE_GLOBAL_CACHE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mpfr_free_cache_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mpfr_free_cache_t.class + " with value " + swigValue);
  }

  private mpfr_free_cache_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mpfr_free_cache_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mpfr_free_cache_t(String swigName, mpfr_free_cache_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mpfr_free_cache_t[] swigValues = { MPFR_FREE_LOCAL_CACHE, MPFR_FREE_GLOBAL_CACHE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

