/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public final class mpfr_rnd_t {
  public final static mpfr_rnd_t MPFR_RNDN = new mpfr_rnd_t("MPFR_RNDN", arblibJNI.MPFR_RNDN_get());
  public final static mpfr_rnd_t MPFR_RNDZ = new mpfr_rnd_t("MPFR_RNDZ");
  public final static mpfr_rnd_t MPFR_RNDU = new mpfr_rnd_t("MPFR_RNDU");
  public final static mpfr_rnd_t MPFR_RNDD = new mpfr_rnd_t("MPFR_RNDD");
  public final static mpfr_rnd_t MPFR_RNDA = new mpfr_rnd_t("MPFR_RNDA");
  public final static mpfr_rnd_t MPFR_RNDF = new mpfr_rnd_t("MPFR_RNDF");
  public final static mpfr_rnd_t MPFR_RNDNA = new mpfr_rnd_t("MPFR_RNDNA", arblibJNI.MPFR_RNDNA_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mpfr_rnd_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mpfr_rnd_t.class + " with value " + swigValue);
  }

  private mpfr_rnd_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mpfr_rnd_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mpfr_rnd_t(String swigName, mpfr_rnd_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mpfr_rnd_t[] swigValues = { MPFR_RNDN, MPFR_RNDZ, MPFR_RNDU, MPFR_RNDD, MPFR_RNDA, MPFR_RNDF, MPFR_RNDNA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

