/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class n_ecm_s {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected n_ecm_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(n_ecm_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_n_ecm_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(long value) {
    arblibJNI.n_ecm_s_x_set(swigCPtr, this, value);
  }

  public long getX() {
    return arblibJNI.n_ecm_s_x_get(swigCPtr, this);
  }

  public void setZ(long value) {
    arblibJNI.n_ecm_s_z_set(swigCPtr, this, value);
  }

  public long getZ() {
    return arblibJNI.n_ecm_s_z_get(swigCPtr, this);
  }

  public void setA24(long value) {
    arblibJNI.n_ecm_s_a24_set(swigCPtr, this, value);
  }

  public long getA24() {
    return arblibJNI.n_ecm_s_a24_get(swigCPtr, this);
  }

  public void setNinv(long value) {
    arblibJNI.n_ecm_s_ninv_set(swigCPtr, this, value);
  }

  public long getNinv() {
    return arblibJNI.n_ecm_s_ninv_get(swigCPtr, this);
  }

  public void setNormbits(long value) {
    arblibJNI.n_ecm_s_normbits_set(swigCPtr, this, value);
  }

  public long getNormbits() {
    return arblibJNI.n_ecm_s_normbits_get(swigCPtr, this);
  }

  public void setOne(long value) {
    arblibJNI.n_ecm_s_one_set(swigCPtr, this, value);
  }

  public long getOne() {
    return arblibJNI.n_ecm_s_one_get(swigCPtr, this);
  }

  public void setGCD_table(SWIGTYPE_p_unsigned_char value) {
    arblibJNI.n_ecm_s_GCD_table_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getGCD_table() {
    long cPtr = arblibJNI.n_ecm_s_GCD_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setPrime_table(SWIGTYPE_p_p_unsigned_char value) {
    arblibJNI.n_ecm_s_prime_table_set(swigCPtr, this, SWIGTYPE_p_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_unsigned_char getPrime_table() {
    long cPtr = arblibJNI.n_ecm_s_prime_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_unsigned_char(cPtr, false);
  }

  public n_ecm_s() {
    this(arblibJNI.new_n_ecm_s(), true);
  }

}
