/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class n_factor_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected n_factor_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(n_factor_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_n_factor_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum(int value) {
    arblibJNI.n_factor_t_num_set(swigCPtr, this, value);
  }

  public int getNum() {
    return arblibJNI.n_factor_t_num_get(swigCPtr, this);
  }

  public void setExp(SWIGTYPE_p_int value) {
    arblibJNI.n_factor_t_exp_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getExp() {
    long cPtr = arblibJNI.n_factor_t_exp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setP(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.n_factor_t_p_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getP() {
    long cPtr = arblibJNI.n_factor_t_p_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public n_factor_t() {
    this(arblibJNI.new_n_factor_t(), true);
  }

}
