/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class n_pair_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected n_pair_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(n_pair_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_n_pair_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(long value) {
    arblibJNI.n_pair_t_x_set(swigCPtr, this, value);
  }

  public long getX() {
    return arblibJNI.n_pair_t_x_get(swigCPtr, this);
  }

  public void setY(long value) {
    arblibJNI.n_pair_t_y_set(swigCPtr, this, value);
  }

  public long getY() {
    return arblibJNI.n_pair_t_y_get(swigCPtr, this);
  }

  public n_pair_t() {
    this(arblibJNI.new_n_pair_t(), true);
  }

}
