/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class n_primes_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected n_primes_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(n_primes_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_n_primes_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSmall_i(int value) {
    arblibJNI.n_primes_struct_small_i_set(swigCPtr, this, value);
  }

  public int getSmall_i() {
    return arblibJNI.n_primes_struct_small_i_get(swigCPtr, this);
  }

  public void setSmall_num(int value) {
    arblibJNI.n_primes_struct_small_num_set(swigCPtr, this, value);
  }

  public int getSmall_num() {
    return arblibJNI.n_primes_struct_small_num_get(swigCPtr, this);
  }

  public void setSmall_primes(SWIGTYPE_p_unsigned_int value) {
    arblibJNI.n_primes_struct_small_primes_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getSmall_primes() {
    long cPtr = arblibJNI.n_primes_struct_small_primes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setSieve_a(long value) {
    arblibJNI.n_primes_struct_sieve_a_set(swigCPtr, this, value);
  }

  public long getSieve_a() {
    return arblibJNI.n_primes_struct_sieve_a_get(swigCPtr, this);
  }

  public void setSieve_b(long value) {
    arblibJNI.n_primes_struct_sieve_b_set(swigCPtr, this, value);
  }

  public long getSieve_b() {
    return arblibJNI.n_primes_struct_sieve_b_get(swigCPtr, this);
  }

  public void setSieve_i(int value) {
    arblibJNI.n_primes_struct_sieve_i_set(swigCPtr, this, value);
  }

  public int getSieve_i() {
    return arblibJNI.n_primes_struct_sieve_i_get(swigCPtr, this);
  }

  public void setSieve_num(int value) {
    arblibJNI.n_primes_struct_sieve_num_set(swigCPtr, this, value);
  }

  public int getSieve_num() {
    return arblibJNI.n_primes_struct_sieve_num_get(swigCPtr, this);
  }

  public void setSieve(String value) {
    arblibJNI.n_primes_struct_sieve_set(swigCPtr, this, value);
  }

  public String getSieve() {
    return arblibJNI.n_primes_struct_sieve_get(swigCPtr, this);
  }

  public n_primes_struct() {
    this(arblibJNI.new_n_primes_struct(), true);
  }

}
