/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_poly_res_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_poly_res_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_poly_res_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_poly_res_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRes(long value) {
    arblibJNI.nmod_poly_res_struct_res_set(swigCPtr, this, value);
  }

  public long getRes() {
    return arblibJNI.nmod_poly_res_struct_res_get(swigCPtr, this);
  }

  public void setLc(long value) {
    arblibJNI.nmod_poly_res_struct_lc_set(swigCPtr, this, value);
  }

  public long getLc() {
    return arblibJNI.nmod_poly_res_struct_lc_get(swigCPtr, this);
  }

  public void setLen0(int value) {
    arblibJNI.nmod_poly_res_struct_len0_set(swigCPtr, this, value);
  }

  public int getLen0() {
    return arblibJNI.nmod_poly_res_struct_len0_get(swigCPtr, this);
  }

  public void setLen1(int value) {
    arblibJNI.nmod_poly_res_struct_len1_set(swigCPtr, this, value);
  }

  public int getLen1() {
    return arblibJNI.nmod_poly_res_struct_len1_get(swigCPtr, this);
  }

  public void setOff(int value) {
    arblibJNI.nmod_poly_res_struct_off_set(swigCPtr, this, value);
  }

  public int getOff() {
    return arblibJNI.nmod_poly_res_struct_off_get(swigCPtr, this);
  }

  public nmod_poly_res_struct() {
    this(arblibJNI.new_nmod_poly_res_struct(), true);
  }

}
