/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_poly_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_poly_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_poly_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_poly_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCoeffs(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.nmod_poly_struct_coeffs_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getCoeffs() {
    long cPtr = arblibJNI.nmod_poly_struct_coeffs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setAlloc(int value) {
    arblibJNI.nmod_poly_struct_alloc_set(swigCPtr, this, value);
  }

  public int getAlloc() {
    return arblibJNI.nmod_poly_struct_alloc_get(swigCPtr, this);
  }

  public void setLength(int value) {
    arblibJNI.nmod_poly_struct_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return arblibJNI.nmod_poly_struct_length_get(swigCPtr, this);
  }

  public void setMod(nmod_t value) {
    arblibJNI.nmod_poly_struct_mod_set(swigCPtr, this, nmod_t.getCPtr(value), value);
  }

  public nmod_t getMod() {
    long cPtr = arblibJNI.nmod_poly_struct_mod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_t(cPtr, false);
  }

  public nmod_poly_struct() {
    this(arblibJNI.new_nmod_poly_struct(), true);
  }

}
