/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_poly_matrix_precompute_arg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_poly_matrix_precompute_arg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_poly_matrix_precompute_arg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_poly_matrix_precompute_arg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setA(nmod_mat_struct value) {
    arblibJNI.nmod_poly_matrix_precompute_arg_t_A_set(swigCPtr, this, nmod_mat_struct.getCPtr(value), value);
  }

  public nmod_mat_struct getA() {
    long cPtr = arblibJNI.nmod_poly_matrix_precompute_arg_t_A_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_mat_struct(cPtr, false);
  }

  public void setPoly1(nmod_poly_struct value) {
    arblibJNI.nmod_poly_matrix_precompute_arg_t_poly1_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getPoly1() {
    long cPtr = arblibJNI.nmod_poly_matrix_precompute_arg_t_poly1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setPoly2(nmod_poly_struct value) {
    arblibJNI.nmod_poly_matrix_precompute_arg_t_poly2_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getPoly2() {
    long cPtr = arblibJNI.nmod_poly_matrix_precompute_arg_t_poly2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setPoly2inv(nmod_poly_struct value) {
    arblibJNI.nmod_poly_matrix_precompute_arg_t_poly2inv_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getPoly2inv() {
    long cPtr = arblibJNI.nmod_poly_matrix_precompute_arg_t_poly2inv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public nmod_poly_matrix_precompute_arg_t() {
    this(arblibJNI.new_nmod_poly_matrix_precompute_arg_t(), true);
  }

}
