/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setN(long value) {
    arblibJNI.nmod_t_n_set(swigCPtr, this, value);
  }

  public long getN() {
    return arblibJNI.nmod_t_n_get(swigCPtr, this);
  }

  public void setNinv(long value) {
    arblibJNI.nmod_t_ninv_set(swigCPtr, this, value);
  }

  public long getNinv() {
    return arblibJNI.nmod_t_ninv_get(swigCPtr, this);
  }

  public void setNorm(long value) {
    arblibJNI.nmod_t_norm_set(swigCPtr, this, value);
  }

  public long getNorm() {
    return arblibJNI.nmod_t_norm_get(swigCPtr, this);
  }

  public nmod_t() {
    this(arblibJNI.new_nmod_t(), true);
  }

}
