/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_discrete_log_pohlig_hellman_table_entry_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_discrete_log_pohlig_hellman_table_entry_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_discrete_log_pohlig_hellman_table_entry_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_discrete_log_pohlig_hellman_table_entry_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGammapow(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_table_entry_struct_gammapow_set(swigCPtr, this, value);
  }

  public long getGammapow() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_table_entry_struct_gammapow_get(swigCPtr, this);
  }

  public void setCm(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_table_entry_struct_cm_set(swigCPtr, this, value);
  }

  public long getCm() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_table_entry_struct_cm_get(swigCPtr, this);
  }

  public nmod_discrete_log_pohlig_hellman_table_entry_struct() {
    this(arblibJNI.new_nmod_discrete_log_pohlig_hellman_table_entry_struct(), true);
  }

}
