/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_discrete_log_pohlig_hellman_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_discrete_log_pohlig_hellman_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_discrete_log_pohlig_hellman_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_discrete_log_pohlig_hellman_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMod(nmod_t value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_struct_mod_set(swigCPtr, this, nmod_t.getCPtr(value), value);
  }

  public nmod_t getMod() {
    long cPtr = arblibJNI.nmod_discrete_log_pohlig_hellman_struct_mod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_t(cPtr, false);
  }

  public void setAlpha(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_struct_alpha_set(swigCPtr, this, value);
  }

  public long getAlpha() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_struct_alpha_get(swigCPtr, this);
  }

  public void setAlphainv(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_struct_alphainv_set(swigCPtr, this, value);
  }

  public long getAlphainv() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_struct_alphainv_get(swigCPtr, this);
  }

  public void setNum_factors(int value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_struct_num_factors_set(swigCPtr, this, value);
  }

  public int getNum_factors() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_struct_num_factors_get(swigCPtr, this);
  }

  public void setEntries(nmod_discrete_log_pohlig_hellman_entry_struct value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_struct_entries_set(swigCPtr, this, nmod_discrete_log_pohlig_hellman_entry_struct.getCPtr(value), value);
  }

  public nmod_discrete_log_pohlig_hellman_entry_struct getEntries() {
    long cPtr = arblibJNI.nmod_discrete_log_pohlig_hellman_struct_entries_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_discrete_log_pohlig_hellman_entry_struct(cPtr, false);
  }

  public nmod_discrete_log_pohlig_hellman_struct() {
    this(arblibJNI.new_nmod_discrete_log_pohlig_hellman_struct(), true);
  }

}
