/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_poly_interval_poly_arg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_poly_interval_poly_arg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_poly_interval_poly_arg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_poly_interval_poly_arg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBaby(nmod_poly_struct value) {
    arblibJNI.nmod_poly_interval_poly_arg_t_baby_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getBaby() {
    long cPtr = arblibJNI.nmod_poly_interval_poly_arg_t_baby_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setRes(nmod_poly_struct value) {
    arblibJNI.nmod_poly_interval_poly_arg_t_res_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getRes() {
    long cPtr = arblibJNI.nmod_poly_interval_poly_arg_t_res_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setH(nmod_poly_struct value) {
    arblibJNI.nmod_poly_interval_poly_arg_t_H_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getH() {
    long cPtr = arblibJNI.nmod_poly_interval_poly_arg_t_H_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setV(nmod_poly_struct value) {
    arblibJNI.nmod_poly_interval_poly_arg_t_v_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getV() {
    long cPtr = arblibJNI.nmod_poly_interval_poly_arg_t_v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setVinv(nmod_poly_struct value) {
    arblibJNI.nmod_poly_interval_poly_arg_t_vinv_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getVinv() {
    long cPtr = arblibJNI.nmod_poly_interval_poly_arg_t_vinv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setTmp(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.nmod_poly_interval_poly_arg_t_tmp_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getTmp() {
    long cPtr = arblibJNI.nmod_poly_interval_poly_arg_t_tmp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setM(int value) {
    arblibJNI.nmod_poly_interval_poly_arg_t_m_set(swigCPtr, this, value);
  }

  public int getM() {
    return arblibJNI.nmod_poly_interval_poly_arg_t_m_get(swigCPtr, this);
  }

  public nmod_poly_interval_poly_arg_t() {
    this(arblibJNI.new_nmod_poly_interval_poly_arg_t(), true);
  }

}
