/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_berlekamp_massey_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_berlekamp_massey_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_berlekamp_massey_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_berlekamp_massey_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNpoints(int value) {
    arblibJNI.nmod_berlekamp_massey_struct_npoints_set(swigCPtr, this, value);
  }

  public int getNpoints() {
    return arblibJNI.nmod_berlekamp_massey_struct_npoints_get(swigCPtr, this);
  }

  public void setR0(nmod_poly_struct value) {
    arblibJNI.nmod_berlekamp_massey_struct_R0_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getR0() {
    long cPtr = arblibJNI.nmod_berlekamp_massey_struct_R0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setR1(nmod_poly_struct value) {
    arblibJNI.nmod_berlekamp_massey_struct_R1_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getR1() {
    long cPtr = arblibJNI.nmod_berlekamp_massey_struct_R1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setV0(nmod_poly_struct value) {
    arblibJNI.nmod_berlekamp_massey_struct_V0_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getV0() {
    long cPtr = arblibJNI.nmod_berlekamp_massey_struct_V0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setV1(nmod_poly_struct value) {
    arblibJNI.nmod_berlekamp_massey_struct_V1_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getV1() {
    long cPtr = arblibJNI.nmod_berlekamp_massey_struct_V1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setQt(nmod_poly_struct value) {
    arblibJNI.nmod_berlekamp_massey_struct_qt_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getQt() {
    long cPtr = arblibJNI.nmod_berlekamp_massey_struct_qt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setRt(nmod_poly_struct value) {
    arblibJNI.nmod_berlekamp_massey_struct_rt_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getRt() {
    long cPtr = arblibJNI.nmod_berlekamp_massey_struct_rt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public void setPoints(nmod_poly_struct value) {
    arblibJNI.nmod_berlekamp_massey_struct_points_set(swigCPtr, this, nmod_poly_struct.getCPtr(value), value);
  }

  public nmod_poly_struct getPoints() {
    long cPtr = arblibJNI.nmod_berlekamp_massey_struct_points_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_poly_struct(cPtr, false);
  }

  public nmod_berlekamp_massey_struct() {
    this(arblibJNI.new_nmod_berlekamp_massey_struct(), true);
  }

}
