/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class nmod_discrete_log_pohlig_hellman_entry_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nmod_discrete_log_pohlig_hellman_entry_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nmod_discrete_log_pohlig_hellman_entry_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_nmod_discrete_log_pohlig_hellman_entry_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExp(int value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_exp_set(swigCPtr, this, value);
  }

  public int getExp() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_exp_get(swigCPtr, this);
  }

  public void setPrime(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_prime_set(swigCPtr, this, value);
  }

  public long getPrime() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_prime_get(swigCPtr, this);
  }

  public void setGamma(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_gamma_set(swigCPtr, this, value);
  }

  public long getGamma() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_gamma_get(swigCPtr, this);
  }

  public void setGammainv(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_gammainv_set(swigCPtr, this, value);
  }

  public long getGammainv() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_gammainv_get(swigCPtr, this);
  }

  public void setStartingbeta(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_startingbeta_set(swigCPtr, this, value);
  }

  public long getStartingbeta() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_startingbeta_get(swigCPtr, this);
  }

  public void setCo(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_co_set(swigCPtr, this, value);
  }

  public long getCo() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_co_get(swigCPtr, this);
  }

  public void setStartinge(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_startinge_set(swigCPtr, this, value);
  }

  public long getStartinge() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_startinge_get(swigCPtr, this);
  }

  public void setIdem(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_idem_set(swigCPtr, this, value);
  }

  public long getIdem() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_idem_get(swigCPtr, this);
  }

  public void setCbound(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_cbound_set(swigCPtr, this, value);
  }

  public long getCbound() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_cbound_get(swigCPtr, this);
  }

  public void setDbound(long value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_dbound_set(swigCPtr, this, value);
  }

  public long getDbound() {
    return arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_dbound_get(swigCPtr, this);
  }

  public void setTable(nmod_discrete_log_pohlig_hellman_table_entry_struct value) {
    arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_table_set(swigCPtr, this, nmod_discrete_log_pohlig_hellman_table_entry_struct.getCPtr(value), value);
  }

  public nmod_discrete_log_pohlig_hellman_table_entry_struct getTable() {
    long cPtr = arblibJNI.nmod_discrete_log_pohlig_hellman_entry_struct_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nmod_discrete_log_pohlig_hellman_table_entry_struct(cPtr, false);
  }

  public nmod_discrete_log_pohlig_hellman_entry_struct() {
    this(arblibJNI.new_nmod_discrete_log_pohlig_hellman_entry_struct(), true);
  }

}
