/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class pthread_rwlock_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected pthread_rwlock_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pthread_rwlock_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_pthread_rwlock_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set__data(__pthread_rwlock_arch_t value) {
    arblibJNI.pthread_rwlock_t___data_set(swigCPtr, this, __pthread_rwlock_arch_t.getCPtr(value), value);
  }

  public __pthread_rwlock_arch_t get__data() {
    long cPtr = arblibJNI.pthread_rwlock_t___data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __pthread_rwlock_arch_t(cPtr, false);
  }

  public void set__size(String value) {
    arblibJNI.pthread_rwlock_t___size_set(swigCPtr, this, value);
  }

  public String get__size() {
    return arblibJNI.pthread_rwlock_t___size_get(swigCPtr, this);
  }

  public void set__align(int value) {
    arblibJNI.pthread_rwlock_t___align_set(swigCPtr, this, value);
  }

  public int get__align() {
    return arblibJNI.pthread_rwlock_t___align_get(swigCPtr, this);
  }

  public pthread_rwlock_t() {
    this(arblibJNI.new_pthread_rwlock_t(), true);
  }

}
