/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class random_data {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected random_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(random_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_random_data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFptr(SWIGTYPE_p_int value) {
    arblibJNI.random_data_fptr_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFptr() {
    long cPtr = arblibJNI.random_data_fptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setRptr(SWIGTYPE_p_int value) {
    arblibJNI.random_data_rptr_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getRptr() {
    long cPtr = arblibJNI.random_data_rptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setState(SWIGTYPE_p_int value) {
    arblibJNI.random_data_state_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getState() {
    long cPtr = arblibJNI.random_data_state_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setRand_type(int value) {
    arblibJNI.random_data_rand_type_set(swigCPtr, this, value);
  }

  public int getRand_type() {
    return arblibJNI.random_data_rand_type_get(swigCPtr, this);
  }

  public void setRand_deg(int value) {
    arblibJNI.random_data_rand_deg_set(swigCPtr, this, value);
  }

  public int getRand_deg() {
    return arblibJNI.random_data_rand_deg_get(swigCPtr, this);
  }

  public void setRand_sep(int value) {
    arblibJNI.random_data_rand_sep_set(swigCPtr, this, value);
  }

  public int getRand_sep() {
    return arblibJNI.random_data_rand_sep_get(swigCPtr, this);
  }

  public void setEnd_ptr(SWIGTYPE_p_int value) {
    arblibJNI.random_data_end_ptr_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getEnd_ptr() {
    long cPtr = arblibJNI.random_data_end_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public random_data() {
    this(arblibJNI.new_random_data(), true);
  }

}
