/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class sigaction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sigaction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sigaction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_sigaction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSa_handler(SWIGTYPE_p_f_int__void value) {
    arblibJNI.sigaction_sa_handler_set(swigCPtr, this, SWIGTYPE_p_f_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__void getSa_handler() {
    long cPtr = arblibJNI.sigaction_sa_handler_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__void(cPtr, false);
  }

  public void setSa_flags(long value) {
    arblibJNI.sigaction_sa_flags_set(swigCPtr, this, value);
  }

  public long getSa_flags() {
    return arblibJNI.sigaction_sa_flags_get(swigCPtr, this);
  }

  public void setSa_restorer(SWIGTYPE_p_f_void__void value) {
    arblibJNI.sigaction_sa_restorer_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getSa_restorer() {
    long cPtr = arblibJNI.sigaction_sa_restorer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setSa_mask(__sigset_t value) {
    arblibJNI.sigaction_sa_mask_set(swigCPtr, this, __sigset_t.getCPtr(value), value);
  }

  public __sigset_t getSa_mask() {
    long cPtr = arblibJNI.sigaction_sa_mask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __sigset_t(cPtr, false);
  }

  public sigaction() {
    this(arblibJNI.new_sigaction(), true);
  }

}
