/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class sigevent_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sigevent_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sigevent_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_sigevent_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSigev_value(sigval_t value) {
    arblibJNI.sigevent_t_sigev_value_set(swigCPtr, this, sigval_t.getCPtr(value), value);
  }

  public sigval_t getSigev_value() {
    long cPtr = arblibJNI.sigevent_t_sigev_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new sigval_t(cPtr, false);
  }

  public void setSigev_signo(int value) {
    arblibJNI.sigevent_t_sigev_signo_set(swigCPtr, this, value);
  }

  public int getSigev_signo() {
    return arblibJNI.sigevent_t_sigev_signo_get(swigCPtr, this);
  }

  public void setSigev_notify(int value) {
    arblibJNI.sigevent_t_sigev_notify_set(swigCPtr, this, value);
  }

  public int getSigev_notify() {
    return arblibJNI.sigevent_t_sigev_notify_get(swigCPtr, this);
  }

  public sigevent_t() {
    this(arblibJNI.new_sigevent_t(), true);
  }

}
