/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class siginfo_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected siginfo_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(siginfo_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_siginfo_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSi_signo(int value) {
    arblibJNI.siginfo_t_si_signo_set(swigCPtr, this, value);
  }

  public int getSi_signo() {
    return arblibJNI.siginfo_t_si_signo_get(swigCPtr, this);
  }

  public void setSi_errno(int value) {
    arblibJNI.siginfo_t_si_errno_set(swigCPtr, this, value);
  }

  public int getSi_errno() {
    return arblibJNI.siginfo_t_si_errno_get(swigCPtr, this);
  }

  public void setSi_code(int value) {
    arblibJNI.siginfo_t_si_code_set(swigCPtr, this, value);
  }

  public int getSi_code() {
    return arblibJNI.siginfo_t_si_code_get(swigCPtr, this);
  }

  public void set_sifields(__sifields value) {
    arblibJNI.siginfo_t__sifields_set(swigCPtr, this, __sifields.getCPtr(value), value);
  }

  public __sifields get_sifields() {
    long cPtr = arblibJNI.siginfo_t__sifields_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __sifields(cPtr, false);
  }

  public void set_si_pad(SWIGTYPE_p_int value) {
    arblibJNI.siginfo_t__si_pad_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int get_si_pad() {
    long cPtr = arblibJNI.siginfo_t__si_pad_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public siginfo_t() {
    this(arblibJNI.new_siginfo_t(), true);
  }

}
