/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class sigval_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sigval_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sigval_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_sigval_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSival_int(int value) {
    arblibJNI.sigval_t_sival_int_set(swigCPtr, this, value);
  }

  public int getSival_int() {
    return arblibJNI.sigval_t_sival_int_get(swigCPtr, this);
  }

  public void setSival_ptr(SWIGTYPE_p_void value) {
    arblibJNI.sigval_t_sival_ptr_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getSival_ptr() {
    long cPtr = arblibJNI.sigval_t_sival_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public sigval_t() {
    this(arblibJNI.new_sigval_t(), true);
  }

}
