/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class stack_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected stack_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(stack_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_stack_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSs_sp(SWIGTYPE_p_void value) {
    arblibJNI.stack_t_ss_sp_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getSs_sp() {
    long cPtr = arblibJNI.stack_t_ss_sp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setSs_flags(int value) {
    arblibJNI.stack_t_ss_flags_set(swigCPtr, this, value);
  }

  public int getSs_flags() {
    return arblibJNI.stack_t_ss_flags_get(swigCPtr, this);
  }

  public void setSs_size(long value) {
    arblibJNI.stack_t_ss_size_set(swigCPtr, this, value);
  }

  public long getSs_size() {
    return arblibJNI.stack_t_ss_size_get(swigCPtr, this);
  }

  public stack_t() {
    this(arblibJNI.new_stack_t(), true);
  }

}
