/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class SWIGTYPE_p___jmp_buf_tag {
  private transient long swigCPtr;

  protected SWIGTYPE_p___jmp_buf_tag(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p___jmp_buf_tag() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p___jmp_buf_tag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

