/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class thread_pool_struct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected thread_pool_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(thread_pool_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_thread_pool_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOriginal_affinity(SWIGTYPE_p_cpu_set_t value) {
    arblibJNI.thread_pool_struct_original_affinity_set(swigCPtr, this, SWIGTYPE_p_cpu_set_t.getCPtr(value));
  }

  public SWIGTYPE_p_cpu_set_t getOriginal_affinity() {
    return new SWIGTYPE_p_cpu_set_t(arblibJNI.thread_pool_struct_original_affinity_get(swigCPtr, this), true);
  }

  public void setMutex(pthread_mutex_t value) {
    arblibJNI.thread_pool_struct_mutex_set(swigCPtr, this, pthread_mutex_t.getCPtr(value), value);
  }

  public pthread_mutex_t getMutex() {
    long cPtr = arblibJNI.thread_pool_struct_mutex_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pthread_mutex_t(cPtr, false);
  }

  public void setTdata(thread_pool_entry_struct value) {
    arblibJNI.thread_pool_struct_tdata_set(swigCPtr, this, thread_pool_entry_struct.getCPtr(value), value);
  }

  public thread_pool_entry_struct getTdata() {
    long cPtr = arblibJNI.thread_pool_struct_tdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new thread_pool_entry_struct(cPtr, false);
  }

  public void setLength(int value) {
    arblibJNI.thread_pool_struct_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return arblibJNI.thread_pool_struct_length_get(swigCPtr, this);
  }

  public thread_pool_struct() {
    this(arblibJNI.new_thread_pool_struct(), true);
  }

}
