/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class timezone {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected timezone(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(timezone obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_timezone(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTz_minuteswest(int value) {
    arblibJNI.timezone_tz_minuteswest_set(swigCPtr, this, value);
  }

  public int getTz_minuteswest() {
    return arblibJNI.timezone_tz_minuteswest_get(swigCPtr, this);
  }

  public void setTz_dsttime(int value) {
    arblibJNI.timezone_tz_dsttime_set(swigCPtr, this, value);
  }

  public int getTz_dsttime() {
    return arblibJNI.timezone_tz_dsttime_get(swigCPtr, this);
  }

  public timezone() {
    this(arblibJNI.new_timezone(), true);
  }

}
