/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class timespec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected timespec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(timespec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_timespec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTv_sec(int value) {
    arblibJNI.timespec_tv_sec_set(swigCPtr, this, value);
  }

  public int getTv_sec() {
    return arblibJNI.timespec_tv_sec_get(swigCPtr, this);
  }

  public void setTv_nsec(int value) {
    arblibJNI.timespec_tv_nsec_set(swigCPtr, this, value);
  }

  public int getTv_nsec() {
    return arblibJNI.timespec_tv_nsec_get(swigCPtr, this);
  }

  public timespec() {
    this(arblibJNI.new_timespec(), true);
  }

}
